// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Hector Tarrido-Picart

/// Menu category for a command. Single taxonomy feeding the menu bar, the
/// (future) toolbar, and the command palette. Every registry verb maps to
/// exactly one category (asserted by `menu_grouping_has_no_orphans` in the app).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Category {
    File,
    Edit,
    View,
    Draw2d,
    Curve,
    Solid,
    Boolean,
    Transform,
    Annotate,
    Dimension,
    Analyze,
    Structure,
    Tools,
}

impl Category {
    /// Stable machine name (used for grouping keys and tests).
    pub fn key(self) -> &'static str {
        match self {
            Category::File => "File",
            Category::Edit => "Edit",
            Category::View => "View",
            Category::Draw2d => "Draw2d",
            Category::Curve => "Curve",
            Category::Solid => "Solid",
            Category::Boolean => "Boolean",
            Category::Transform => "Transform",
            Category::Annotate => "Annotate",
            Category::Dimension => "Dimension",
            Category::Analyze => "Analyze",
            Category::Structure => "Structure",
            Category::Tools => "Tools",
        }
    }
}

/// One entry per command verb. Single source of truth for command-line help,
/// the LLM system prompt (`deck` renders this table into the prompt), AND the
/// registry-driven menu bar / toolbar (via `category`).
pub struct CommandSpec {
    pub name: &'static str,
    pub usage: &'static str,
    pub summary: &'static str,
    pub category: Category,
}

pub fn registry() -> &'static [CommandSpec] {
    &[
        CommandSpec {
            name: "box",
            usage: "box <corner x,y,z> <size x,y,z>",
            summary: "Axis-aligned box. Example: box 0,0,0 5,5,3",
            category: Category::Solid,
        },
        CommandSpec {
            name: "extrude",
            usage: "extrude <selector> <height>",
            summary: "Extrude a closed profile curve upward. Example: extrude last 3",
            category: Category::Solid,
        },
        CommandSpec {
            name: "revolve",
            usage: "revolve <selector> [axis point x,y,z] [axis dir x,y,z] [angle deg]",
            summary: "Revolve one closed profile curve into a solid (default: full circle about the z axis through the origin; partial angles are capped). Draw the profile beside the axis, e.g. in the xz plane with x,0,z points. Example: revolve last · revolve vase 0,0,0 0,0,1 270",
            category: Category::Solid,
        },
        CommandSpec {
            name: "loft",
            usage: "loft <selector>",
            summary: "Skin 2+ closed curves (stacked in creation order) into one capped solid; profiles are resampled to matching point counts. Example: loft last 3",
            category: Category::Solid,
        },
        CommandSpec {
            name: "sweep",
            usage: "sweep <profile selector> <rail selector>",
            summary: "Sweep one closed profile curve along an open rail curve (profile centered on the rail, no-twist frames, capped ends). Example: sweep prof rail",
            category: Category::Solid,
        },
        CommandSpec {
            name: "sweep2",
            usage: "sweep2 <profile selector> <rail-a selector> <rail-b selector>",
            summary: "Sweep one closed profile between two open rails, lofting it so its ends track both rails at every station (profile width scales to the rail gap). Capped, watertight. Example: sweep2 prof railA railB",
            category: Category::Solid,
        },
        CommandSpec {
            name: "railrevolve",
            usage: "railrevolve <profile selector> <rail selector> <axis point x,y,z> <axis dir x,y,z>",
            summary: "Revolve one closed profile about an axis where the radius follows a rail curve (nearest-angle radius). Full turn. Example: railrevolve prof rail 0,0,0 0,0,1",
            category: Category::Solid,
        },
        CommandSpec {
            name: "pipe",
            usage: "pipe <curve selector> <radius> [end radius]",
            summary: "Sweep a circular profile along a curve with a linearly interpolated radius (variable-radius pipe). Capped, watertight. Example: pipe path 2 · pipe path 2 0.5",
            category: Category::Solid,
        },
        CommandSpec {
            name: "line",
            usage: "line <a x,y,z> <b x,y,z>",
            summary: "Line segment. Example: line 0,0,0 10,0,0",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "polyline",
            usage: "polyline <p1> <p2> ... [closed]",
            summary: "Polyline through points; append 'closed' to close it. Example: polyline 0,0 5,0 5,5 closed",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "rect",
            usage: "rect <corner x,y,z> <width> <height>",
            summary: "Rectangle in the XY plane. Example: rect 0,0,0 4 6",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "circle",
            usage: "circle <center x,y,z> <radius>",
            summary: "Circle in the XY plane. Example: circle 0,0,0 2.5",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "arc",
            usage: "arc <center x,y,z> <radius> <start deg> <end deg>",
            summary: "CCW arc in the XY plane. Example: arc 0,0,0 5 0 90",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "ellipse",
            usage: "ellipse <center x,y,z> <rx> <ry>",
            summary: "Ellipse in the XY plane. Example: ellipse 0,0,0 4 2",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "polygon",
            usage: "polygon <center x,y,z> <radius> <sides>",
            summary: "Regular polygon in the XY plane. Example: polygon 0,0,0 3 6",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "curve",
            usage: "curve <p1> <p2> <p3> ... [degree N]",
            summary: "NURBS curve by control points (default degree 3). Example: curve 0,0 2,4 6,4 8,0",
            category: Category::Curve,
        },
        CommandSpec {
            name: "interpcurve",
            usage: "interpcurve <p1> <p2> <p3> ... [closed]",
            summary: "C2 cubic curve passing through the points exactly. Append 'closed' for a loop. Example: interpcurve 0,0 2,4 6,4 8,0 10,2",
            category: Category::Curve,
        },
        CommandSpec {
            name: "helix",
            usage: "helix <center x,y,z> <radius> <height> <turns>",
            summary: "3D helix about +Z (dense polyline). Example: helix 0,0,0 3 12 4",
            category: Category::Curve,
        },
        CommandSpec {
            name: "setpoint",
            usage: "setpoint <curve selector> <index> <x,y,z>",
            summary: "Move one control/vertex point of a NURBS or polyline curve. Example: setpoint last 2 4,5,0",
            category: Category::Curve,
        },
        CommandSpec {
            name: "rebuild",
            usage: "rebuild <curve selector> <count>",
            summary: "Resample a curve to N evenly-spaced points (polyline). Example: rebuild last 20",
            category: Category::Curve,
        },
        CommandSpec {
            name: "dim",
            usage: "dim <a x,y,z> <b x,y,z> [offset]",
            summary: "Linear dimension between two points; the measured distance is displayed automatically. Offset (default 0.5) places the dimension line left of a->b. Example: dim 0,0 10,0 0.8",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "text",
            usage: "text <pos x,y,z> <words...> [height]",
            summary: "Text annotation at a point; trailing number = text height in meters (default 0.2). Example: text 5,3 living room 0.3",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "hatch",
            usage: "hatch <selector> [solid | lines [angle spacing] | crosshatch [angle spacing] | brick [spacing] | concrete [spacing] | insulation [spacing] | earth [spacing]]",
            summary: "Hatch the region of a closed curve. Patterns: solid (fill), lines (parallel, default 45° 0.25m), crosshatch (two perpendicular sets), brick (running bond, horizontal courses), concrete (dash-dot scatter), insulation (batt zigzag), earth (45° short dashes). Example: hatch last · hatch last brick 0.2 · hatch last insulation 0.3",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "union",
            usage: "union <selector>",
            summary: "Merge 2+ meshes into one solid; inputs are consumed. Example: union last 2",
            category: Category::Boolean,
        },
        CommandSpec {
            name: "difference",
            usage: "difference <target selector> <tool selector>",
            summary: "Subtract tool meshes from target meshes (cut holes, courtyards); inputs are consumed and tools win overlapping selectors. Make the tool slightly taller/deeper than the target for clean through-cuts. Examples: difference tower core · difference last 2 last",
            category: Category::Boolean,
        },
        CommandSpec {
            name: "intersect",
            usage: "intersect <selector>",
            summary: "Keep only the shared volume of 2+ meshes; inputs are consumed. Example: intersect last 2",
            category: Category::Boolean,
        },
        CommandSpec {
            name: "section",
            usage: "section <selector> <plane point x,y,z> <normal x,y,z>  |  section <name> rect <w> <h> | circle <d> | iwf <d> <bf> <tf> <tw> | pipe <d> <t>",
            summary: "Two uses. (1) Plane cut: cut meshes with a plane; each closed loop becomes a heavy polyline on layer 'sections'. Example: section all 0,0,1.2 0,0,1. (2) Structural section: define a named cross-section (profile) for beam/column members, chosen by a shape keyword in second position — rect (solid rectangle), circle, iwf (I / wide-flange: depth, flange width, flange thickness, web thickness), pipe (hollow round). Example: section W12 iwf 0.31 0.2 0.013 0.008 · section col rect 0.4 0.4",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "plan",
            usage: "plan <height>",
            summary: "Architect's plan cut: horizontal section of every mesh at the given height; wall outlines and courtyard holes land as heavy closed polylines on layer 'sections', and edges of geometry below the cut (furniture, floor) are projected down as thin polylines on 'sections-proj'. Cut ~1.2m above the floor of interest. Example: plan 1.2 · plan 4.7 (second floor at 3.5m + 1.2m)",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "elevation",
            usage: "elevation <north|south|east|west> [depth]",
            summary: "Orthographic side-view outline: feature edges of all geometry projected onto the vertical plane for the compass direction (no cutting), as thin polylines on layer 'elevations'. 'north' is the face seen looking south. Example: elevation south · elevation east 2",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "move",
            usage: "move <selector> <delta x,y,z>",
            summary: "Translate objects. Example: move last 5,0,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "rotate",
            usage: "rotate <selector> <angle deg> [x|y|z] [about <x,y,z>]",
            summary: "Rotate objects (default: about z through their bounding-box center). Example: rotate last 45 · rotate all 90 x about 0,0,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "scale",
            usage: "scale <selector> <factor | fx,fy,fz> [about <x,y,z>]",
            summary: "Scale objects uniformly or per-axis (default: about their bounding-box center). Example: scale last 2 · scale last 1,1,2",
            category: Category::Transform,
        },
        CommandSpec {
            name: "split",
            usage: "split <selector> <point x,y>",
            summary: "Split a curve in two at the nearest point on it to the given point; the original is replaced by the pieces. Example: split last 5,0",
            category: Category::Curve,
        },
        CommandSpec {
            name: "trim",
            usage: "trim <target selector> <cutter selector> <keep point x,y>",
            summary: "Cut a curve where it crosses the cutter curve(s) and keep only the piece nearest the keep point; the rest is removed. Example: trim wall slab 1,1",
            category: Category::Curve,
        },
        CommandSpec {
            name: "extend",
            usage: "extend <selector> <distance>",
            summary: "Extend both open ends of curves by a distance (lines/polylines tangentially, arcs along their circle). Example: extend last 0.5",
            category: Category::Curve,
        },
        CommandSpec {
            name: "join",
            usage: "join <selector>",
            summary: "Join end-touching curves (1e-6 gap tolerance) into one polyline; inputs are consumed, arcs are tessellated. Example: join last 3",
            category: Category::Curve,
        },
        CommandSpec {
            name: "fillet",
            usage: "fillet <a selector> <b selector> <radius> | fillet <selector matching 2> <radius>",
            summary: "Round the corner between two lines with a tangent arc, trimming both lines to the tangency points. Example: fillet last 2 0.5",
            category: Category::Curve,
        },
        CommandSpec {
            name: "offset",
            usage: "offset <selector> <distance>",
            summary: "Offset a curve in the XY plane; original kept. Closed curves: positive = outward, negative = inward (walls from centerlines: offset both ways, extrude). Example: offset last 0.2",
            category: Category::Curve,
        },
        CommandSpec {
            name: "mirror",
            usage: "mirror <selector> <xy|yz|xz | point normal>",
            summary: "Mirror objects across a plane. Example: mirror last yz · mirror last 0,5,0 0,1,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "copy",
            usage: "copy <selector> <delta x,y,z>",
            summary: "Duplicate objects with an offset. Example: copy last 6,0,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "array",
            usage: "array <selector> <nx,ny,nz> <dx,dy,dz>",
            summary: "Grid of copies at the given spacings; the originals fill cell 0,0,0 (nx,ny works too, nz=1). Example: box 0,0,0 0.4,0.4,3 then array last 5,3,1 3,4,0 makes a 5x3 column grid at 3m x 4m bays",
            category: Category::Transform,
        },
        CommandSpec {
            name: "polararray",
            usage: "polararray <selector> <count> [center x,y,z] [total angle deg]",
            summary: "Circular array of copies about the z axis (default: full circle about the targets' bounding-box center; count includes the original). Example: polararray last 8 · polararray col 6 0,0,0 180",
            category: Category::Transform,
        },
        CommandSpec {
            name: "delete",
            usage: "delete <selector>",
            summary: "Delete objects. Example: delete last",
            category: Category::Edit,
        },
        CommandSpec {
            name: "group",
            usage: "group <selector> [name]",
            summary: "Group objects under a name (auto-named group1, group2... when omitted). Clicking any member selects the whole group, and the group name works as a selector. Example: group last 2 boxes",
            category: Category::Edit,
        },
        CommandSpec {
            name: "ungroup",
            usage: "ungroup <selector>",
            summary: "Dissolve every group containing the selected objects; the objects themselves stay. Example: ungroup boxes",
            category: Category::Edit,
        },
        CommandSpec {
            name: "name",
            usage: "name <selector> <name>",
            summary: "Name objects for later reference. Example: name last tower-a",
            category: Category::Edit,
        },
        CommandSpec {
            name: "layer",
            usage: "layer <name>",
            summary: "Create (if needed) and switch the current layer; new objects land on it. Example: layer walls",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "tolayer",
            usage: "tolayer <selector> <name>",
            summary: "Move objects onto a layer (created if needed). Example: tolayer last 2 structure",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layercolor",
            usage: "layercolor <layer> <r,g,b>",
            summary: "Set a layer's display color, 0-1 or 0-255 values. Example: layercolor walls 0.8,0.2,0.1",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layerweight",
            usage: "layerweight <layer> <mm>",
            summary: "Set a layer's print lineweight in mm (controls PDF stroke width and DXF code-370). Default 0.18 mm; sections layer convention is 0.35 mm. Example: layerweight sections 0.35",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "hide",
            usage: "hide <layer>",
            summary: "Hide a layer (objects stay in the model, invisible). Example: hide walls",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "show",
            usage: "show <layer>",
            summary: "Show a hidden layer. Example: show walls",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "hideobj",
            usage: "hideobj <selector>",
            summary: "Hide individual objects (they stay in the model, invisible and unpickable). Example: hideobj last 2",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "showobj",
            usage: "showobj <selector>",
            summary: "Show hidden objects ('showobj all' reveals everything). Example: showobj all",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "color",
            usage: "color <selector> <r,g,b | off>",
            summary: "Set or clear a per-object color override (0-1 or 0-255 values). Beats the layer color. 'color last off' clears it. Example: color last 1,0.3,0 · color walls off",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "units",
            usage: "units <m|cm|mm|ft|in|ftin>",
            summary: "Set the display unit for dimensions and readouts (geometry stays meters internally). Number suffixes work everywhere regardless: 500mm, 2.5m, 12ft, 6in, and feet-inches typed as 12ft6in (shown as 12'-6\"). Example: units ftin",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "underlay",
            usage: "underlay <path.png> [corner x,y] [width]",
            summary: "Place a raster image (PNG) flat on the ground plane to trace over; corner is the lower-left in meters (default 0,0), width in meters (default 10, height follows the image aspect). Example: underlay /tmp/site.png 0,0 20",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlayopacity",
            usage: "underlayopacity <0..1>",
            summary: "Set the underlay's blend opacity. Example: underlayopacity 0.4",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlayoff",
            usage: "underlayoff",
            summary: "Remove the underlay image",
            category: Category::Tools,
        },
        CommandSpec {
            name: "sun",
            usage: "sun <lat> <lon> <YYYY-MM-DD> <HH:MM>",
            summary: "Set solar lighting by computing azimuth + altitude (NOAA simplified SPA) for the given observer location and UTC time. The renderer shades meshes from that direction. Example: sun 40.71 -74.01 2024-06-21 14:00",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sunoff",
            usage: "sunoff",
            summary: "Remove solar lighting; revert to headlight shading",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "location",
            usage: "location <lat> <lon> [tz-hours]",
            summary: "Set the observer location (used by shadowstudy/sunhours). tz is UTC offset in hours (default 0). Example: location 40.71 -74.01 -5",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "shadowstudy",
            usage: "shadowstudy <YYYY-MM-DD> <from-HH:MM> <to-HH:MM> <step-min>",
            summary: "Cast ground shadows of every mesh onto z=0 for each time step across a day, one closed polygon (projected convex hull per object) per stamp on 'shadows-HH:MM' layers. Needs a location (sun/location/EPW). Example: shadowstudy 2024-06-21 09:00 15:00 120",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sunhours",
            usage: "sunhours <YYYY-MM-DD> [grid-spacing]",
            summary: "Sunlight-hours heatmap: sample a ground grid over the scene, ray-cast toward the sun every 30 min of the date, and color a mesh overlay on 'analysis' (blue = few hours, red = most). Default spacing 2 m. Needs a location. Example: sunhours 2024-06-21 1.5",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sheet",
            usage: "sheet <name> [a4|a3|a2|a1|a0]",
            summary: "Create a named paper sheet, landscape (default a3). Example: sheet plan a1",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "sheetview",
            usage: "sheetview <sheet> <top|front|right|persp> <scale>",
            summary: "Add a scaled ortho view to a sheet; scale is 1:100 or 100 (1m = 10mm at 1:100). Example: sheetview plan top 1:100",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "print",
            usage: "print <sheet> <path.pdf>",
            summary: "Export a sheet as a vector PDF at its views' scales. Example: print plan /tmp/plan.pdf",
            category: Category::File,
        },
        CommandSpec {
            name: "export",
            usage: "export <path.{dxf|stl|obj|gltf|glb|svg|csv|ifc}>",
            summary: "Export the whole document, format chosen by extension: DXF R12 (2D entities, meshes as feature edges), binary STL and glTF/GLB (triangle meshes only), OBJ (meshes plus curves as polylines), SVG, CSV, or IFC4 openBIM (mesh objects as IfcBuildingElementProxy for Revit/BlenderBIM). Example: export /tmp/model.ifc",
            category: Category::File,
        },
        CommandSpec {
            name: "import",
            usage: "import <path.{dxf|obj|stl|gltf|glb|ifc|epw|geojson|las}>",
            summary: "Import a file by extension: DXF (LINE, LWPOLYLINE, POLYLINE, CIRCLE, ARC, TEXT → logged ops), OBJ/STL/glTF/GLB meshes, IFC4/IFC2x3 (meshes → the 'ifc' layer), EPW EnergyPlus weather (sets the document location and reports annual stats), GeoJSON (Polygon → closed polyline, LineString → polyline, Point → 0.5m marker circle; properties.name → object name; lon/lat projected to local meters when a location is set, else treated as local xy), or LAS 1.2–1.4 point cloud (formats 0–3; decimated to ≤200k points; stored on layer 'pointcloud'; LAZ not supported). Example: import /tmp/site.las",
            category: Category::File,
        },
        CommandSpec {
            name: "terrain",
            usage: "terrain <path.{csv|geojson}>",
            summary: "Build a terrain surface mesh on layer 'terrain'. .csv = Delaunay-triangulate x,y,z survey points (header row optional). .geojson = triangulate the vertices of elevation contour LineStrings (elevation read from the 'elevation' or 'ele' property; lon/lat projected when a location is set). Example: terrain /tmp/survey.csv",
            category: Category::Tools,
        },
        CommandSpec {
            name: "osmfile",
            usage: "osmfile <path.json>",
            summary: "Build OpenStreetMap building context from a saved Overpass API JSON export ('out geom;' query): each building-tagged way footprint is extruded (height tag, else building:levels x 3 m, else 9 m) into a mesh on layer 'context'. lon/lat projected to local meters when a location is set. Example: osmfile /tmp/overpass.json",
            category: Category::Tools,
        },
        CommandSpec {
            name: "distance",
            usage: "distance <a x,y,z> <b x,y,z>",
            summary: "Measure the distance between two points (query only, nothing is created). Example: distance 0,0,0 3,4,0",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "area",
            usage: "area <selector>",
            summary: "Measure area: closed curves report the enclosed XY area, meshes their total surface area (query only). Example: area last",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "volume",
            usage: "volume <selector>",
            summary: "Measure the volume of solid meshes (query only). Example: volume last",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "bbox",
            usage: "bbox <selector>",
            summary: "Report the combined bounding box (min, max, size) of objects (query only). Example: bbox all",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "schedule",
            usage: "schedule [layer]",
            summary: "Print a schedule table (name/id/layer/type/area/volume) for all objects or a layer's objects, grouped by name (query only). Example: schedule · schedule walls",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sheettable",
            usage: "sheettable <sheet> [layer]",
            summary: "Place a schedule table on a sheet; the table is rendered as a text grid in the PDF at print time. Example: sheettable plan · sheettable plan walls",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "sheetdim",
            usage: "sheetdim <sheet> <x1,y1> <x2,y2> [offset_mm]",
            summary: "Add a paper-space linear dimension to a sheet; a and b are paper coordinates in mm, offset is the perpendicular dim-line offset in mm (default 8). The numeric label is derived from the model distance via the view scale. Example: sheetdim plan 20,30 120,30 10",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "view",
            usage: "view save <name> | view <name> | view list",
            summary: "Named views: save the active viewport camera, restore it later, or list saved views. Example: view save entry then view entry",
            category: Category::View,
        },
        CommandSpec {
            name: "block",
            usage: "block <selector> <name>",
            summary: "Capture the geometry of selected objects as a named reusable block definition (like a symbol/component). Inputs stay in the scene; the definition is a geometry snapshot. Example: block last door · block last 3 tree (architect: door, window, tree, column, stair)",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "insert",
            usage: "insert <name> <position x,y,z> [rotation_deg] [scale]",
            summary: "Place an instance of a named block at a point with optional rotation (degrees CCW about Z) and uniform scale. Instances move/scale/rotate as a single object. Example: insert door 3,0,0 · insert tree 10,5,0 0 0.8 · insert column 0,0,0 90 1",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "blocks",
            usage: "blocks",
            summary: "List all block definitions with their geometry counts (query only). Example: blocks",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "blocklib",
            usage: "blocklib [list]",
            summary: "List block names in the on-disk library (~/.config/itsjustcad/blocks/). Example: blocklib",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "blockload",
            usage: "blockload <name>",
            summary: "Load a library block into the document as a named definition ready to insert. Example: blockload tree · blockload door-single",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "blocksave",
            usage: "blocksave <name> [description]",
            summary: "Save the named block definition from the document back to the library. Example: blocksave my-column 'precast column 400mm'",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "select",
            usage: "select <selector>",
            summary: "Set the selection. Example: select all",
            category: Category::Edit,
        },
        CommandSpec {
            name: "selectnone",
            usage: "selectnone",
            summary: "Clear the selection",
            category: Category::Edit,
        },
        CommandSpec {
            name: "undo",
            usage: "undo",
            summary: "Undo the last geometry command",
            category: Category::Edit,
        },
        CommandSpec {
            name: "redo",
            usage: "redo",
            summary: "Redo",
            category: Category::Edit,
        },
        CommandSpec {
            name: "amend",
            usage: "amend <step> <command...>",
            summary: "Rewrite history: replace the op at <step> (0 = first op) with a new command and replay the whole log; later ops rebuild against the change. On failure nothing changes. Example: amend 0 box 0,0,0 8,8,3",
            category: Category::Edit,
        },
        CommandSpec {
            name: "option",
            usage: "option save <name> | option <name> | option list | option delete <name>",
            summary: "Design options: named branches of the op-log for comparing schemes. 'option save tower' snapshots the current model as a branch; 'option courtyard' switches to (replays) another branch, auto-saving in-progress work to the branch you leave first; 'option list' shows branches (* = current); 'option delete <name>' removes one. Example: box 0,0,0 5,5,20 then option save tower",
            category: Category::Edit,
        },
        CommandSpec {
            name: "material",
            usage: "material <name> <elastic-modulus-E> <density>",
            summary: "Define a named structural material (stored for interoperability, never analyzed here). E in Pa, density in kg/m³. Example: material steel 200e9 7850 · material concrete 30e9 2400",
            category: Category::Structure,
        },
        CommandSpec {
            name: "grid",
            usage: "grid <name> x A:0 B:5 ... y 1:0 2:4 ... [levels 0,3,6]",
            summary: "Define a labeled reference grid: X axes and Y axes as label:coord pairs, plus optional level elevations. Rendered as reference lines. Example: grid main x A:0 B:6 C:12 y 1:0 2:5 levels 0,3.5,7",
            category: Category::Structure,
        },
        CommandSpec {
            name: "story",
            usage: "story <name> <elevation>",
            summary: "Define a building story/level by name and elevation (meters); stored sorted by elevation. Example: story L1 0 · story L2 3.5",
            category: Category::Structure,
        },
        CommandSpec {
            name: "beam",
            usage: "beam <a x,y,z> <b x,y,z> <section> [material <m>] [rot <deg>]",
            summary: "Frame member (horizontal): sweep a named section along the line a→b into a solid. Optional material and roll angle (deg). Example: beam 0,0,3 6,0,3 W12 material steel · beam 0,0,3 6,0,3 col rot 90",
            category: Category::Structure,
        },
        CommandSpec {
            name: "column",
            usage: "column <a x,y,z> <b x,y,z> <section> [material <m>] [rot <deg>]",
            summary: "Frame member (vertical): sweep a named section along the line a→b into a solid. Same as beam, distinct for scheduling/ergonomics. Example: column 0,0,0 0,0,3.5 col material concrete",
            category: Category::Structure,
        },
        CommandSpec {
            name: "slab",
            usage: "slab <p1> <p2> <p3> ... thick <t> [material <m>]",
            summary: "Area member: extrude a closed boundary upward (+Z) by thickness into a floor slab. Example: slab 0,0 6,0 6,4 0,4 thick 0.2 material concrete",
            category: Category::Structure,
        },
        CommandSpec {
            name: "wall",
            usage: "wall <p1> <p2> <p3> ... thick <t> [material <m>]",
            summary: "Area member: extrude a closed boundary along its horizontal normal by thickness into a wall. Example: wall 0,0 6,0 6,0.2 0,0.2 thick 3 material concrete",
            category: Category::Structure,
        },
    ]
}

/// Selector grammar shared by help and the LLM prompt.
pub const SELECTOR_HELP: &str =
    "Selectors: 'last' (most recent object), 'last N' (N most recent), 'all', 'sel' (current selection), or an object name.";
