// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Hector Tarrido-Picart

/// Menu category for a command. Single taxonomy feeding the menu bar, the
/// (future) toolbar, and the command palette. Every registry verb maps to
/// exactly one category (asserted by `menu_grouping_has_no_orphans` in the app).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Category {
    File,
    Edit,
    View,
    Draw2d,
    Curve,
    Solid,
    Boolean,
    Transform,
    Annotate,
    Dimension,
    Analyze,
    Structure,
    Tools,
}

impl Category {
    /// Stable machine name (used for grouping keys and tests).
    pub fn key(self) -> &'static str {
        match self {
            Category::File => "File",
            Category::Edit => "Edit",
            Category::View => "View",
            Category::Draw2d => "Draw2d",
            Category::Curve => "Curve",
            Category::Solid => "Solid",
            Category::Boolean => "Boolean",
            Category::Transform => "Transform",
            Category::Annotate => "Annotate",
            Category::Dimension => "Dimension",
            Category::Analyze => "Analyze",
            Category::Structure => "Structure",
            Category::Tools => "Tools",
        }
    }
}

/// One entry per command verb. Single source of truth for command-line help,
/// the LLM system prompt (`deck` renders this table into the prompt), AND the
/// registry-driven menu bar / toolbar (via `category`).
pub struct CommandSpec {
    pub name: &'static str,
    pub usage: &'static str,
    pub summary: &'static str,
    pub category: Category,
}

pub fn registry() -> &'static [CommandSpec] {
    &[
        CommandSpec {
            name: "box",
            usage: "box <corner x,y,z> <size x,y,z>",
            summary: "Axis-aligned box. Example: box 0,0,0 5,5,3",
            category: Category::Solid,
        },
        CommandSpec {
            name: "extrude",
            usage: "extrude <selector> <height>",
            summary: "Extrude a closed profile curve upward. Example: extrude last 3",
            category: Category::Solid,
        },
        CommandSpec {
            name: "revolve",
            usage: "revolve <selector> [axis point x,y,z] [axis dir x,y,z] [angle deg]",
            summary: "Revolve one closed profile curve into a solid (default: full circle about the z axis through the origin; partial angles are capped). Draw the profile beside the axis, e.g. in the xz plane with x,0,z points. Example: revolve last · revolve vase 0,0,0 0,0,1 270",
            category: Category::Solid,
        },
        CommandSpec {
            name: "loft",
            usage: "loft <selector> [guides <selector>]",
            summary: "Skin 2+ closed curves (stacked in creation order) into one capped solid; profiles are resampled to matching point counts. Optional open guide curves (first profile -> last) bow the skin through them. Example: loft last 3 · loft name:rings guides name:rail",
            category: Category::Solid,
        },
        CommandSpec {
            name: "blend",
            usage: "blend <curve a> <curve b> [bulge]",
            summary: "Blend surface between two curves (both open or both closed): a Hermite-eased sheet taking off perpendicular to each edge. Bulge 1 (default) = ruled surface, >1 eases harder off the edges. Example: blend name:top name:bottom 1.5",
            category: Category::Solid,
        },
        CommandSpec {
            name: "sweep",
            usage: "sweep <profile selector> <rail selector>",
            summary: "Sweep one closed profile curve along an open rail curve (profile centered on the rail, no-twist frames, capped ends). Example: sweep prof rail",
            category: Category::Solid,
        },
        CommandSpec {
            name: "sweep2",
            usage: "sweep2 <profile selector> <rail-a selector> <rail-b selector>",
            summary: "Sweep one closed profile between two open rails, lofting it so its ends track both rails at every station (profile width scales to the rail gap). Capped, watertight. Example: sweep2 prof railA railB",
            category: Category::Solid,
        },
        CommandSpec {
            name: "railrevolve",
            usage: "railrevolve <profile selector> <rail selector> <axis point x,y,z> <axis dir x,y,z>",
            summary: "Revolve one closed profile about an axis where the radius follows a rail curve (nearest-angle radius). Full turn. Example: railrevolve prof rail 0,0,0 0,0,1",
            category: Category::Solid,
        },
        CommandSpec {
            name: "pipe",
            usage: "pipe <curve selector> <radius> [end radius]",
            summary: "Sweep a circular profile along a curve with a linearly interpolated radius (variable-radius pipe). Capped, watertight. Example: pipe path 2 · pipe path 2 0.5",
            category: Category::Solid,
        },
        CommandSpec {
            name: "geodesic",
            usage: "geodesic <frequency> <radius> [dome|full]",
            summary: "Geodesic dome/sphere (Buckminster Fuller): subdivide an icosahedron 'frequency' times, project to a sphere of 'radius', render edges as struts. 'dome' (default) keeps the upper hemisphere; 'full' builds the whole sphere. Example: geodesic 3 5 dome",
            category: Category::Structure,
        },
        CommandSpec {
            name: "spaceframe",
            usage: "spaceframe <nx> <ny> <bay> <depth>",
            summary: "Double-layer space-frame grid: nx×ny bays at 'bay' spacing, top and offset bottom chord layers 'depth' apart, tied by pyramid diagonals. Example: spaceframe 6 4 3 1.5",
            category: Category::Structure,
        },
        CommandSpec {
            name: "hypar",
            usage: "hypar <a> <b> <c> [nu] [nv]",
            summary: "Hyperbolic-paraboloid (Candela) saddle shell z = x*y/c over [-a,a]×[-b,b], meshed nu×nv (default 12). Example: hypar 5 5 5",
            category: Category::Structure,
        },
        CommandSpec {
            name: "gaussvault",
            usage: "gaussvault <span> <length> <rise> [undulate]",
            summary: "Gaussian catenary brick vault (Dieste): a catenary section of 'span'/'rise' swept along 'length'; add 'undulate' for the signature sinusoidal double-curvature. Example: gaussvault 6 12 3 undulate",
            category: Category::Structure,
        },
        CommandSpec {
            name: "gridshell",
            usage: "gridshell hypar <a> <b> <c> [nu] [nv] | gridshell vault <span> <length> <rise> [undulate] [nu] [nv]",
            summary: "Lattice of laths on a doubly-curved surface (a hypar or a gauss vault), rendered as a reciprocal net of struts. Example: gridshell hypar 5 5 5 · gridshell vault 6 12 3 undulate",
            category: Category::Structure,
        },
        CommandSpec {
            name: "funicular",
            usage: "funicular <support a> <support b> [segments] [load] [slack] [invert]",
            summary: "Form-finding (dynamic relaxation): hang a chain between two supports under gravity to find the catenary/funicular shape; add 'invert' to flip it into the pure-compression arch/shell (Gaudí: hang the chain, stand the arch). Example: funicular -5,0,0 5,0,0 24 1 1.4 invert",
            category: Category::Structure,
        },
        CommandSpec {
            name: "tensegrity",
            usage: "tensegrity <struts> [radius] [height] [twist deg]",
            summary: "Form-finding: isolated compression struts in a continuous tension cable net, relaxed to the stable prestressed equilibrium. Preset 'tensegrity 3' is the classic 3-strut T-prism. Example: tensegrity 3 1 2",
            category: Category::Structure,
        },
        CommandSpec {
            name: "cablenet",
            usage: "cablenet <c0> <c1> <c2> <c3> [n] [sag]",
            summary: "Form-finding: relax an n×n net stretched over four corner anchors to a taut tensile minimal surface (Frei Otto). Example: cablenet 0,0,0 8,0,0 8,8,3 0,8,3 8 1.5",
            category: Category::Structure,
        },
        CommandSpec {
            name: "minsurf",
            usage: "minsurf <closed curve selector> [n]",
            summary: "Form-finding: stretch a soap film (Frei Otto minimal surface) across a selected closed curve — the boundary wire anchors an n×n net of zero-rest-length tension links solved to the harmonic equilibrium surface. The curve is kept. Example: polyline 0,0,1 6,0,-1 6,6,1 0,6,-1 closed then minsurf last",
            category: Category::Structure,
        },
        CommandSpec {
            name: "line",
            usage: "line <a x,y,z> <b x,y,z>",
            summary: "Line segment. Example: line 0,0,0 10,0,0",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "linetan",
            usage: "linetan <from x,y,z> <curve selector>",
            summary: "Line from a point TANGENT to a curve: it runs from the point to the curve's nearest (tangent) point, lying along the curve's tangent there. Example: line 0,0,0 10,0,0 then linetan 5,5,0 last",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "lineperp",
            usage: "lineperp <from x,y,z> <curve selector>",
            summary: "Line from a point PERPENDICULAR to a curve: it runs from the point to the closest point on the curve (the foot of perpendicular). Example: line 0,0,0 10,0,0 then lineperp 5,5,0 last",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "polyline",
            usage: "polyline <p1> <p2> ... [closed]",
            summary: "Polyline through points; append 'closed' to close it. Example: polyline 0,0 5,0 5,5 closed",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "rect",
            usage: "rect <corner x,y,z> <width> <height>",
            summary: "Rectangle in the XY plane. Example: rect 0,0,0 4 6",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "circle",
            usage: "circle <center x,y,z> <radius>",
            summary: "Circle in the XY plane. Example: circle 0,0,0 2.5",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "circletan",
            usage: "circletan <curveA selector> <curveB selector> <radius>",
            summary: "Circle of a given radius tangent to two curves (TTR: tangent-tangent-radius). Supports the line–line case: both lines are offset by the radius and intersected to place the center equidistant from both. Alias: circlettr. Example: line 0,0,0 10,0,0 then name last la then line 0,0,0 0,10,0 then name last lb then circletan la lb 2",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "arc",
            usage: "arc <center x,y,z> <radius> <start deg> <end deg>",
            summary: "CCW arc in the XY plane. Example: arc 0,0,0 5 0 90",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "ellipse",
            usage: "ellipse <center x,y,z> <rx> <ry>",
            summary: "Ellipse in the XY plane. Example: ellipse 0,0,0 4 2",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "polygon",
            usage: "polygon <center x,y,z> <radius> <sides>",
            summary: "Regular polygon in the XY plane. Example: polygon 0,0,0 3 6",
            category: Category::Draw2d,
        },
        CommandSpec {
            name: "curve",
            usage: "curve <p1> <p2> <p3> ... [degree N]",
            summary: "NURBS curve by control points (default degree 3). Example: curve 0,0 2,4 6,4 8,0",
            category: Category::Curve,
        },
        CommandSpec {
            name: "interpcurve",
            usage: "interpcurve <p1> <p2> <p3> ... [closed]",
            summary: "C2 cubic curve passing through the points exactly. Append 'closed' for a loop. Example: interpcurve 0,0 2,4 6,4 8,0 10,2",
            category: Category::Curve,
        },
        CommandSpec {
            name: "helix",
            usage: "helix <center x,y,z> <radius> <height> <turns>",
            summary: "3D helix about +Z (dense polyline). Example: helix 0,0,0 3 12 4",
            category: Category::Curve,
        },
        CommandSpec {
            name: "setpoint",
            usage: "setpoint <curve selector> <index> <x,y,z>",
            summary: "Move one control/vertex point of a NURBS or polyline curve. Example: setpoint last 2 4,5,0",
            category: Category::Curve,
        },
        CommandSpec {
            name: "insertknot",
            usage: "insertknot <curve selector> <t 0..1>",
            summary: "Insert a knot into a NURBS curve at parameter t — shape unchanged, one control point added for finer local editing. Example: insertknot last 0.5",
            category: Category::Curve,
        },
        CommandSpec {
            name: "curvature",
            usage: "curvature <curve selector> [scale] [samples]",
            summary: "Curvature comb: hair lines (length = curvature x scale) plus a tip curve on the 'analysis' layer; reports max curvature / min radius. Scale defaults to auto, samples to 40. Example: curvature last",
            category: Category::Curve,
        },
        CommandSpec {
            name: "rebuild",
            usage: "rebuild <curve selector> <count>",
            summary: "Resample a curve to N evenly-spaced points (polyline). Example: rebuild last 20",
            category: Category::Curve,
        },
        CommandSpec {
            name: "dim",
            usage: "dim <a> <b> [offset]   where each anchor is `x,y,z` or `@<object>.<endpoint>`",
            summary: "Linear dimension between two anchors; the measured distance is displayed automatically. Each anchor is a free point (x,y,z) OR an associative binding @<object>.<endpoint> that follows the referenced object when it moves. <object> is a selector (last, a name, or short id); <endpoint> is start|end|center|cN (bbox corner 0-7)|vN (vertex index). Offset (default 0.5) places the dimension line left of a->b. Examples: dim 0,0 10,0 0.8 · dim @wall.start @wall.end · dim @last.center @beam.end 0.5",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "dimangular",
            usage: "dimangular <vertex x,y,z> <p1 x,y,z> <p2 x,y,z> [radius]",
            summary: "Angular dimension: measures the angle p1-vertex-p2 and labels it in degrees, drawing an arc of the given radius (default 1.0) between the two legs. Points are free model points. Example: dimangular 0,0 1,0 0,1  (a 90° corner)",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "text",
            usage: "text <pos x,y,z> <words...> [height]",
            summary: "Text annotation at a point; trailing number = text height in meters (default 0.2). Example: text 5,3 living room 0.3",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "field",
            usage: "field <pos x,y,z> <expr> [height]   where expr is: area <sel> | length <sel> | count <sel> | layer | units",
            summary: "FIELD text: text at a point bound to a live value that auto-updates after edits (mirrors associative dims). expr := area <sel> (closed-curve/mesh area) | length <sel> (curve length) | count <sel> (number of matched objects) | layer (current layer) | units (unit symbol). <sel> is a single-object selector (last, a name, or a short id). Trailing number = height (default 0.2). Examples: field 5,3 area last · field 0,0 count all · field 2,2 length wall 0.3",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "hatch",
            usage: "hatch <selector> [solid | lines [angle spacing] | crosshatch [angle spacing] | brick [spacing] | concrete [spacing] | insulation [spacing] | earth [spacing] | ansi31..ansi38 [spacing]]",
            summary: "Hatch the region of a closed curve. Patterns: solid (fill), lines (parallel, default 45° 0.25m), crosshatch (two perpendicular sets), brick (running bond, horizontal courses), concrete (dash-dot scatter), insulation (batt zigzag), earth (45° short dashes), ANSI standard set ansi31-ansi38 (31 iron, 32 steel, 33 bronze/brass, 34 plastic/rubber, 35 fire brick, 36 marble/glass, 37 lead/zinc, 38 aluminum; default spacing 0.2m). Example: hatch last · hatch last brick 0.2 · hatch last ansi32",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "boundary",
            usage: "boundary <seed x,y,z> [from <selector>]",
            summary: "AutoCAD BOUNDARY: pick a point inside a region enclosed by existing curves and create a closed boundary polyline (then hatch/extrude it). Traces the smallest loop around the seed in the XY plane. `from <selector>` limits the candidate curves; otherwise all curves are used. Example: boundary 5,3 · boundary 5,3 from all",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "curvebool",
            usage: "curvebool <union|intersect|difference> <selector>",
            summary: "Rhino CurveBoolean: combine 2+ closed planar curves into new closed region curve(s). union merges the outer boundary of the combined area; intersect keeps the overlap; difference is the first selected curve minus the rest (selection order). Works in the XY plane (planar assumption; Z carried from the first input). Inputs are consumed and replaced by the result (undoable). Op aliases: or/and/sub. Verb aliases: cboolean/region. Example: curvebool union last 2 · curvebool intersect all · curvebool difference last 2",
            category: Category::Boolean,
        },
        CommandSpec {
            name: "union",
            usage: "union <selector>",
            summary: "Merge 2+ meshes into one solid; inputs are consumed. Example: union last 2",
            category: Category::Boolean,
        },
        CommandSpec {
            name: "difference",
            usage: "difference <target selector> <tool selector>",
            summary: "Subtract tool meshes from target meshes (cut holes, courtyards); inputs are consumed and tools win overlapping selectors. Make the tool slightly taller/deeper than the target for clean through-cuts. Examples: difference tower core · difference last 2 last",
            category: Category::Boolean,
        },
        CommandSpec {
            name: "intersect",
            usage: "intersect <selector>",
            summary: "Keep only the shared volume of 2+ meshes; inputs are consumed. Example: intersect last 2",
            category: Category::Boolean,
        },
        CommandSpec {
            name: "exact_boolean",
            usage: "exact_boolean <union|difference|intersection> <a_corner x,y,z> <a_size x,y,z> <b_corner x,y,z> <b_size x,y,z>",
            summary: "Exact-BREP boolean of two axis-aligned boxes using the opt-in OCCT kernel (feature 'kernel-occt'); falls back to the mesh kernel when OCCT is not compiled in, noting the fallback. Retains an exact volume. Example: exact_boolean difference 0,0,0 10,10,10 3,3,-5 4,4,20",
            category: Category::Boolean,
        },
        CommandSpec {
            name: "section",
            usage: "section <selector> <plane point x,y,z> <normal x,y,z>  |  section <name> rect <w> <h> | circle <d> | iwf <d> <bf> <tf> <tw> | pipe <d> <t>",
            summary: "Two uses. (1) Plane cut: cut meshes with a plane; each closed loop becomes a heavy polyline on layer 'sections'. Example: section all 0,0,1.2 0,0,1. (2) Structural section: define a named cross-section (profile) for beam/column members, chosen by a shape keyword in second position — rect (solid rectangle), circle, iwf (I / wide-flange: depth, flange width, flange thickness, web thickness), pipe (hollow round). Example: section W12 iwf 0.31 0.2 0.013 0.008 · section col rect 0.4 0.4",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "plan",
            usage: "plan <height>",
            summary: "Architect's plan cut: horizontal section of every mesh at the given height; wall outlines and courtyard holes land as heavy closed polylines on layer 'sections', and edges of geometry below the cut (furniture, floor) are projected down as thin polylines on 'sections-proj'. Cut ~1.2m above the floor of interest. Example: plan 1.2 · plan 4.7 (second floor at 3.5m + 1.2m)",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "elevation",
            usage: "elevation <north|south|east|west> [depth]",
            summary: "Orthographic side-view outline: feature edges of all geometry projected onto the vertical plane for the compass direction (no cutting), as thin polylines on layer 'elevations'. 'north' is the face seen looking south. Example: elevation south · elevation east 2",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "move",
            usage: "move <selector> <delta x,y,z>",
            summary: "Translate objects. Example: move last 5,0,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "rotate",
            usage: "rotate <selector> <angle deg> [x|y|z] [about <x,y,z>]",
            summary: "Rotate objects (default: about z through their bounding-box center). Example: rotate last 45 · rotate all 90 x about 0,0,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "scale",
            usage: "scale <selector> <factor | fx,fy,fz> [about <x,y,z>]",
            summary: "Scale objects uniformly or per-axis (default: about their bounding-box center). Example: scale last 2 · scale last 1,1,2",
            category: Category::Transform,
        },
        CommandSpec {
            name: "align",
            usage: "align <selector> <src1> <tgt1> <src2> <tgt2> [scale on|off]",
            summary: "Orient/align objects (AutoCAD ALIGN / Rhino Orient): move the selection so source reference points match targets. src1→tgt1 sets the translation; the rotation swings the src1→src2 direction onto the tgt1→tgt2 direction (planar, about Z, from the XY headings). 'scale on' also scales uniformly by |tgt2−tgt1|/|src2−src1|; default off. Alias: orient. Example: align last 0,0,0 5,5,0 1,0,0 5,6,0 · align last 0,0,0 0,0,0 1,0,0 2,0,0 scale on",
            category: Category::Transform,
        },
        CommandSpec {
            name: "tozero",
            usage: "tozero <selector>",
            summary: "Move objects so their combined bounding-box minimum sits at the world origin (0,0,0). Alias: toorigin. Example: tozero all",
            category: Category::Transform,
        },
        CommandSpec {
            name: "flatten",
            usage: "flatten <selector>",
            summary: "Project every vertex onto the XY ground plane (set Z=0). Example: flatten last",
            category: Category::Transform,
        },
        CommandSpec {
            name: "stretch",
            usage: "stretch <selector> <min x,y,z> <max x,y,z> <delta x,y,z>",
            summary: "Move only the vertices inside a box by a delta (vertices outside stay put), stretching lines/polylines/point clouds. A tall z-range acts like a 2D crossing window. Curves/points supported; meshes/solids skipped. Example: stretch all 0,0,-10 5,5,10 1,0,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "selsimilar",
            usage: "selsimilar <selector> [layer|color|type|weight]",
            summary: "Select every object sharing a property (default layer) with the current selection: layer, color, type (geometry kind), or weight (effective lineweight). Alias: selsim. Example: selsimilar last color",
            category: Category::Edit,
        },
        CommandSpec {
            name: "seldup",
            usage: "seldup [<selector>]",
            summary: "Select objects that are geometric duplicates of another object (same kind + same points within tolerance, ignoring id/layer) — a precursor to purge. With no selector the whole document is scanned. Alias: selduplicate. Example: seldup",
            category: Category::Edit,
        },
        CommandSpec {
            name: "dimradius",
            usage: "dimradius <selector>",
            summary: "Radial dimension for a circle or arc: from its center to a point on the rim. Alias: dimrad. Example: dimradius last",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "dimdiameter",
            usage: "dimdiameter <selector>",
            summary: "Diameter dimension for a circle or arc: across the full width through its center. Alias: dimdia. Example: dimdiameter last",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "split",
            usage: "split <selector> <point x,y>",
            summary: "Split a curve in two at the nearest point on it to the given point; the original is replaced by the pieces. Example: split last 5,0",
            category: Category::Curve,
        },
        CommandSpec {
            name: "trim",
            usage: "trim <target selector> <cutter selector> <keep point x,y>",
            summary: "Cut a curve where it crosses the cutter curve(s) and keep only the piece nearest the keep point; the rest is removed. Example: trim wall slab 1,1",
            category: Category::Curve,
        },
        CommandSpec {
            name: "powertrim",
            usage: "powertrim <target selector> <pick point x,y>",
            summary: "Trim a curve against ALL other curves at once: split it at every crossing and delete only the segment you pick, keeping the rest (no cutter picking). Example: powertrim wall 5,0",
            category: Category::Curve,
        },
        CommandSpec {
            name: "extend",
            usage: "extend <selector> <distance>",
            summary: "Extend both open ends of curves by a distance (lines/polylines tangentially, arcs along their circle). Example: extend last 0.5",
            category: Category::Curve,
        },
        CommandSpec {
            name: "join",
            usage: "join <selector>",
            summary: "Join end-touching curves (1e-6 gap tolerance) into one polyline; inputs are consumed, arcs are tessellated. Example: join last 3",
            category: Category::Curve,
        },
        CommandSpec {
            name: "constrain",
            usage: "constrain <kind> <selector> [selector] [value]",
            summary: "Add a sketch constraint over lines/circles and re-solve immediately. Kinds: coincident, horizontal, vertical, distance, length, angle (deg), parallel, perpendicular, equal, radius, fixed, tangent, midpoint, on. Endpoint pairs resolve nearest-first. Example: constrain horizontal last · constrain length name:l1 5 · constrain perpendicular name:l1 name:l2",
            category: Category::Curve,
        },
        CommandSpec {
            name: "solveconstraints",
            usage: "solveconstraints",
            summary: "Re-run the sketch-constraint solver over all stored constraints and update the geometry. Reports solved/under-/over-constrained status and remaining degrees of freedom. Example: solveconstraints",
            category: Category::Curve,
        },
        CommandSpec {
            name: "constraints",
            usage: "constraints [list | delete <n> | clear]",
            summary: "List stored sketch constraints with solver status (redundant/conflicting flagged), delete one by number, or clear all. Example: constraints · constraints delete 2 · constraints clear",
            category: Category::Curve,
        },
        CommandSpec {
            name: "fillet",
            usage: "fillet <a selector> <b selector> <radius> | fillet <selector matching 2> <radius>",
            summary: "Round the corner between two lines with a tangent arc, trimming both lines to the tangency points. Example: fillet last 2 0.5",
            category: Category::Curve,
        },
        CommandSpec {
            name: "offset",
            usage: "offset <selector> <distance>",
            summary: "Offset a curve in the XY plane; original kept. Closed curves: positive = outward, negative = inward (walls from centerlines: offset both ways, extrude). Example: offset last 0.2",
            category: Category::Curve,
        },
        CommandSpec {
            name: "mirror",
            usage: "mirror <selector> <xy|yz|xz | point normal>",
            summary: "Mirror objects across a plane. Example: mirror last yz · mirror last 0,5,0 0,1,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "copy",
            usage: "copy <selector> <delta x,y,z>",
            summary: "Duplicate objects with an offset. Example: copy last 6,0,0",
            category: Category::Transform,
        },
        CommandSpec {
            name: "array",
            usage: "array <selector> <nx,ny,nz> <dx,dy,dz>",
            summary: "Grid of copies at the given spacings; the originals fill cell 0,0,0 (nx,ny works too, nz=1). Example: box 0,0,0 0.4,0.4,3 then array last 5,3,1 3,4,0 makes a 5x3 column grid at 3m x 4m bays",
            category: Category::Transform,
        },
        CommandSpec {
            name: "polararray",
            usage: "polararray <selector> <count> [center x,y,z] [total angle deg]",
            summary: "Circular array of copies about the z axis (default: full circle about the targets' bounding-box center; count includes the original). Example: polararray last 8 · polararray col 6 0,0,0 180",
            category: Category::Transform,
        },
        CommandSpec {
            name: "arraycurve",
            usage: "arraycurve <selector> <path-selector> <count> [align on|off]",
            summary: "Distribute copies of the selected object(s) evenly by arc length along a single path curve (endpoints included). With 'align on' (default) each copy rotates so its +X follows the curve tangent; 'align off' translates only. The originals stay put. Example: box 0,0,0 1,1,1 then name last widget then arc 0,0,0 5 0 90 then arraycurve widget last 5",
            category: Category::Transform,
        },
        CommandSpec {
            name: "delete",
            usage: "delete <selector>",
            summary: "Delete objects. Example: delete last",
            category: Category::Edit,
        },
        CommandSpec {
            name: "group",
            usage: "group <selector> [name]",
            summary: "Group objects under a name (auto-named group1, group2... when omitted). Clicking any member selects the whole group, and the group name works as a selector. Example: group last 2 boxes",
            category: Category::Edit,
        },
        CommandSpec {
            name: "ungroup",
            usage: "ungroup <selector>",
            summary: "Dissolve every group containing the selected objects; the objects themselves stay. Example: ungroup boxes",
            category: Category::Edit,
        },
        CommandSpec {
            name: "name",
            usage: "name <selector> <name>",
            summary: "Name objects for later reference. Example: name last tower-a",
            category: Category::Edit,
        },
        CommandSpec {
            name: "layer",
            usage: "layer <name>",
            summary: "Create (if needed) and switch the current layer; new objects land on it. Example: layer walls",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "tolayer",
            usage: "tolayer <selector> <name>",
            summary: "Move objects onto a layer (created if needed). Example: tolayer last 2 structure",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layercolor",
            usage: "layercolor <layer> <r,g,b>",
            summary: "Set a layer's display color, 0-1 or 0-255 values. Example: layercolor walls 0.8,0.2,0.1",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layerweight",
            usage: "layerweight <layer> <mm>",
            summary: "Set a layer's print lineweight in mm (controls PDF stroke width and DXF code-370). Default 0.18 mm; sections layer convention is 0.35 mm. Example: layerweight sections 0.35",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layerrename",
            usage: "layerrename <from> <to>",
            summary: "Rename a layer; its objects and the current-layer pointer follow. Example: layerrename walls exterior",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layerdelete",
            usage: "layerdelete <layer>",
            summary: "Delete a layer; its objects move to the default layer. The default layer cannot be deleted. Example: layerdelete scratch",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layerorder",
            usage: "layerorder <layer> <n>",
            summary: "Set a layer's sort order in the Layers panel (lower shows first). Example: layerorder walls -1",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layerlock",
            usage: "layerlock <layer> <on|off>",
            summary: "Lock/unlock a layer; objects on a locked layer cannot be selected or edited. Example: layerlock walls on",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "layerlinetype",
            usage: "layerlinetype <layer> <continuous|dashed|dotted|dashdot>",
            summary: "Set a layer's linetype pattern (shown in the Layers panel; used by render/export where feasible). Example: layerlinetype grid dashed",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "hide",
            usage: "hide <layer>",
            summary: "Hide a layer (objects stay in the model, invisible). Example: hide walls",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "show",
            usage: "show <layer>",
            summary: "Show a hidden layer. Example: show walls",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "hideobj",
            usage: "hideobj <selector>",
            summary: "Hide individual objects (they stay in the model, invisible and unpickable). Example: hideobj last 2",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "showobj",
            usage: "showobj <selector>",
            summary: "Show hidden objects ('showobj all' reveals everything). Example: showobj all",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "lineweight",
            usage: "lineweight <selector> <mm | iso-name | off>",
            summary: "Set or clear a per-object lineweight override. Beats the layer lineweight in PDF/DXF/SVG export and in the viewport when showweights is on. Accepts raw mm values or ISO pen names: 0.13/0.18/0.25/0.35/0.50/0.70/1.00/1.40/2.00. 'lineweight last off' clears it. Example: lineweight last 0.35 · lineweight walls 0.50 · lineweight last off",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "showweights",
            usage: "showweights <on|off>",
            summary: "Toggle viewport lineweight display. When on, strokes render at their real lineweight (per-object or layer); when off they render as 1-pixel hairlines. Example: showweights on · showweights off",
            category: Category::View,
        },
        CommandSpec {
            name: "color",
            usage: "color <selector> <r,g,b | off>",
            summary: "Set or clear a per-object color override (0-1 or 0-255 values). Beats the layer color. 'color last off' clears it. Example: color last 1,0.3,0 · color walls off",
            category: Category::Annotate,
        },
        CommandSpec {
            // Distinct verb `material2` (NOT `material`): `material` already names
            // the STRUCTURAL material command (elastic modulus + density, used by
            // analysis and IFC). `material2` is a RENDER-ONLY appearance material
            // (base color + roughness + metallic, or a preset) — a different
            // concept, so it gets its own verb rather than overloading `material`.
            name: "material2",
            usage: "material2 <selector> <concrete|glass|metal|wood | roughness=.. metallic=.. color=r,g,b | off>",
            summary: "Set a per-object appearance material for rendering: a preset (concrete/glass/metal/wood) or custom scalars (roughness=0..1, metallic=0..1, color=r,g,b). Presets shade visibly differently (glass smooth, concrete matte, metal specular). 'material2 last off' clears it. Distinct from 'material' (structural E+density). Example: material2 last glass · material2 walls roughness=0.9 metallic=0 color=0.6,0.6,0.6",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "units",
            usage: "units <m|cm|mm|ft|in|ftin>",
            summary: "Set the display unit for dimensions and readouts (geometry stays meters internally). Number suffixes work everywhere regardless: 500mm, 2.5m, 12ft, 6in, and feet-inches typed as 12ft6in (shown as 12'-6\"). Example: units ftin",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "cplane",
            usage: "cplane [world | origin <x,y,z> normal <x,y,z> | 3point <o> <px> <py> | save <name> | <name>]",
            summary: "Construction plane (CPlane/UCS): the frame typed coordinates are measured against. `cplane` reports it; `cplane world` resets to world XY; `cplane origin 0,0,10 normal 0,0,1` lifts the drawing plane to elevation 10; `cplane 3point <origin> <on-X> <in-XY>` builds a frame from three points; `cplane save top` / `cplane top` store & recall. CPlane-aware verbs: line, polyline (any plane); rect, circle, box (translated/upright planes). Logged geometry always stores WORLD coords, so the CPlane never affects replay. Example: cplane origin 0,0,10 normal 0,0,1",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlay",
            usage: "underlay <path.png> [corner x,y] [width]",
            summary: "Place a raster image (PNG) flat on the ground plane to trace over; corner is the lower-left in meters (default 0,0), width in meters (default 10, height follows the image aspect). Example: underlay /tmp/site.png 0,0 20",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlayopacity",
            usage: "underlayopacity <0..1>",
            summary: "Set the underlay's blend opacity. Example: underlayopacity 0.4",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlaymove",
            usage: "underlaymove <dx,dy>",
            summary: "Shift the placed underlay image by dx,dy meters (moves its lower-left corner). Example: underlaymove 2,-3",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlayscale",
            usage: "underlayscale <factor>",
            summary: "Scale the placed underlay's world size about its centre, aspect preserved (>1 grows, <1 shrinks). Example: underlayscale 1.5",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlayrotate",
            usage: "underlayrotate <deg>",
            summary: "Rotate the placed underlay about its centre to an absolute angle in degrees (CCW). Example: underlayrotate 30",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlayplace",
            usage: "underlayplace <x,y> <width_m> [rot_deg]",
            summary: "Reposition + resize the placed underlay in one shot (calibration): set its lower-left corner, width in meters (height follows aspect), and optional rotation. Example: underlayplace 0,0 20 15",
            category: Category::Tools,
        },
        CommandSpec {
            name: "underlayoff",
            usage: "underlayoff",
            summary: "Remove the underlay image",
            category: Category::Tools,
        },
        CommandSpec {
            name: "sun",
            usage: "sun <lat> <lon> <YYYY-MM-DD> <HH:MM>",
            summary: "Set solar lighting by computing azimuth + altitude (NOAA simplified SPA) for the given observer location and UTC time. The renderer shades meshes from that direction. Example: sun 40.71 -74.01 2024-06-21 14:00",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sunoff",
            usage: "sunoff",
            summary: "Remove solar lighting; revert to headlight shading",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "location",
            usage: "location <lat> <lon> [tz-hours]",
            summary: "Set the observer location (used by shadowstudy/sunhours). tz is UTC offset in hours (default 0). Example: location 40.71 -74.01 -5",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "shadowstudy",
            usage: "shadowstudy <YYYY-MM-DD> <from-HH:MM> <to-HH:MM> <step-min>",
            summary: "Cast ground shadows of every mesh onto z=0 for each time step across a day, one closed polygon (projected convex hull per object) per stamp on 'shadows-HH:MM' layers. Needs a location (sun/location/EPW). Example: shadowstudy 2024-06-21 09:00 15:00 120",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sunhours",
            usage: "sunhours <YYYY-MM-DD> [grid-spacing]",
            summary: "Sunlight-hours heatmap: sample a ground grid over the scene, ray-cast toward the sun every 30 min of the date, and color a mesh overlay on 'analysis' (blue = few hours, red = most). Default spacing 2 m. Needs a location. Example: sunhours 2024-06-21 1.5",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "facesunhours",
            usage: "facesunhours <selector> <YYYY-MM-DD>",
            summary: "Per-face insolation: for the selected mesh, ray-cast each triangle toward the sun every 30 min of the date (occlusion-tested against the scene) and color an overlay copy on 'analysis' (blue = few hours, red = most). Reports min/avg/max sun-hours. Needs a location. Example: facesunhours last 2024-06-21",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "radiation",
            usage: "radiation <selector> <path.epw>",
            summary: "Annual radiation study: weight each selected face's beam exposure by the EPW file's hourly Direct-Normal irradiance (occlusion-tested against the scene) plus isotropic-sky diffuse, giving kWh/m2-yr per face. Colors an overlay copy on 'analysis' (blue = least, red = most) and reports min/avg/max. The irradiance bins are embedded in the op-log so replay never needs the EPW again. Needs a location. Example: radiation last site.epw",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sunpath",
            usage: "sunpath [radius] [year]",
            summary: "Sun-path diagram: draw the yearly sun-path dome for the set location as polylines on the 'sunpath' layer — seven date arcs (Dec 21 through Jun 21; Jul-Nov mirror), analemma hour curves, and a horizon compass circle. Radius defaults to 1.2x the scene bounding radius (min 10 m). Needs a location. Example: sunpath · sunpath 25",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "report",
            usage: "report [analysis|codecheck]",
            summary: "Structured summary of the stored analyses: environmental runs (sunhours, facesunhours, radiation, shadowstudy — min/avg/max, distribution, worst/best sample locations) AND compliance runs (`report codecheck` — per-rule verdicts with measured vs required, violating object ids and locations). Run it after an analysis or codecheck to ground design critique in numbers. Compliance output is an advisory pre-check, not a code review. Query only, no geometry. Example: report facesunhours · report codecheck",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "codecheck",
            usage: "codecheck <pack> [story]",
            summary: "Evaluate a compliance-check pack (declarative JSON rules) against the model: ramp/path slope, door clear width, stair risers, headroom, route clear width, turning circles, counts per story, guard drops. Verdicts land in `report codecheck` (rule id, pass/fail/warn, measured vs required, object ids); failures get colored markers on the 'compliance' layer. The embedded 'demo' pack is always available; load more with `checkrules load`. ADVISORY pre-check only, never a code review — verify with a licensed professional / AHJ. Example: codecheck demo · codecheck demo L1",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "checkrules",
            usage: "checkrules list|load <path.json>",
            summary: "Manage compliance-check packs: `list` shows the loaded packs (embedded demo + any loaded this session + ~/.config/itsjustcad/checks/); `load <path>` reads a pack JSON from disk (a named list of rules: id, code ref, severity, target query, geometric predicate, threshold, message — see the demo pack for the schema). Packs are data, LLM-authorable: draft the JSON, save it, `checkrules load` it, then `codecheck <name>`. Example: checkrules load /tmp/ada.checks.json",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sheet",
            usage: "sheet <name> [a4|a3|a2|a1|a0]",
            summary: "Create a named paper sheet, landscape (default a3). Example: sheet plan a1",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "sheetview",
            usage: "sheetview <sheet> <top|front|right|persp> <scale>",
            summary: "Add a scaled ortho view to a sheet; scale is 1:100 or 100 (1m = 10mm at 1:100). Example: sheetview plan top 1:100",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "plotstyle",
            usage: "plotstyle <new <name>|set <name> <layer-or-r,g,b> color <r,g,b> [weight <mm>] [screen <pct>]|list [<name>]|apply <name>|none|delete <name>>",
            summary: "Plot styles / pen tables (AutoCAD CTB/STB): a named, saved mapping from a SOURCE KEY (a layer name, or an object color token 'r,g,b') to how objects PLOT — pen color, lineweight, screening — applied only at print/export, never changing the model. 'new <name>' creates a table; 'set <name> <key> color <r,g,b> [weight <mm>] [screen <pct>]' adds/replaces a mapping (screening 0..100% lightens the pen toward white); 'apply <name>' makes a table the active print pen (looked up per object by layer then color, unmapped objects plot as today); 'none' clears it; 'list [<name>]' shows tables/entries; 'delete <name>' removes one. new/set/apply/none/delete are logged (undoable); list is a query. Example: plotstyle new mono · plotstyle set mono walls color 0,0,0 weight 0.5 · plotstyle apply mono · print plan /tmp/plan.pdf",
            category: Category::File,
        },
        CommandSpec {
            name: "print",
            usage: "print <sheet> <path.pdf>",
            summary: "Export a sheet as a vector PDF at its views' scales. Example: print plan /tmp/plan.pdf",
            category: Category::File,
        },
        CommandSpec {
            name: "sheetset",
            usage: "sheetset <new <name>|add <sheet>|remove <sheet>|order <sheet> <index>|list|publish [<path.pdf>]>",
            summary: "Manage a sheet set — a named, ordered index over existing sheets (AutoCAD Sheet Set Manager). A set only references sheets by name; it never copies their content. Sheet numbers are positional (1-based = order in the set). Sub-commands act on the ACTIVE set (the most recently created): 'new <name>' creates and activates a set; 'add <sheet>' appends an existing sheet; 'remove <sheet>' drops one; 'order <sheet> <index>' moves a sheet to a 1-based slot (renumbering the rest); 'list' shows every set with numbered sheets; 'publish [<path>]' batch-renders every sheet in the active set to a single multi-page PDF (defaults to <setname>.pdf), reusing the print path. new/add/remove/order are logged (undoable); list/publish are query/I-O. Example: sheetset new plans · sheetset add a-101 · sheetset add a-102 · sheetset order a-102 1 · sheetset publish /tmp/plans.pdf",
            category: Category::File,
        },
        CommandSpec {
            name: "export",
            usage: "export <path.{dxf|stl|obj|gltf|glb|svg|csv|ifc|saf|xlsx|3dm|step|stp}>",
            summary: "Export the whole document, format chosen by extension: DXF R12 (2D entities, meshes as feature edges), binary STL and glTF/GLB (triangle meshes only), OBJ (meshes plus curves as polylines), SVG, CSV, IFC4 openBIM (typed IfcBeam/Column/Slab/Wall plus the IfcStructuralAnalysisModel graph for analysis packages), SAF/XLSX (Structural Analysis Format 2.2.0 — genuine .xlsx workbook with SAF sheet names, for handoff to RFEM/SCIA/AxisVM/FEM-Design; geometry+topology only, never analysis results), Rhino 3DM (openNURBS V5 archive: meshes + curves with names and layers; Rhino 5+ opens it), or STEP/STP (AP242 via OCCT — FACETED, one BREP face per triangle; needs the 'kernel-occt' feature). Example: export /tmp/model.xlsx",
            category: Category::File,
        },
        CommandSpec {
            name: "controlimages",
            usage: "controlimages <path-prefix>",
            summary: "Write three control images from the CURRENT view for hand-off to a diffusion / image-editing tool: <prefix>_depth.png (near-to-far depth gradient), <prefix>_edge.png (feature-edge linework), and <prefix>_mask.png (a flat semantic color per layer). CAD-owned control inputs for the diffusion cassette. Example: controlimages /tmp/scene",
            category: Category::File,
        },
        CommandSpec {
            name: "import",
            usage: "import <path.{dwg|dxf|obj|stl|gltf|glb|dae|3dm|step|stp|ifc|epw|geojson|las|laz|e57}>",
            summary: "Import a file by extension. DWG (assisted: auto-invokes a user-installed dwg2dxf/LibreDWG to convert the referenced file to DXF then imports it; needs 'brew install libredwg'; a truncated conversion is rejected with a clear error, never a silent empty import). A bare file NAME (no path) is resolved inside the granted deck workdir (see 'workdir'). DXF (LINE, LWPOLYLINE, POLYLINE, CIRCLE, ARC, TEXT, HATCH, SPLINE, nested block INSERTs → logged ops), OBJ/STL/glTF/GLB meshes, Rhino .3dm (openNURBS: meshes → MeshLiteral, lines/polylines/NURBS curves → Polyline, on their Rhino layer; breps/surfaces skipped), STEP/STP (AP242/AP203/AP214 exact BREP solids via OCCT — read exactly then tessellated to a MeshLiteral with the exact volume reported; needs the 'kernel-occt' feature), IFC4/IFC2x3 (meshes → the 'ifc' layer), EPW EnergyPlus weather (sets the document location and reports annual stats), GeoJSON (Polygon → closed polyline, LineString → polyline, Point → 0.5m marker circle; properties.name → object name; lon/lat projected to local meters when a location is set, else treated as local xy), LAS 1.2–1.4 or compressed LAZ point cloud (formats 0–3; decimated to ≤200k points; stored on layer 'pointcloud'), or E57 point cloud (ASTM E2807; Cartesian + optional RGB/intensity; all sections merged; decimated to ≤200k; stored on layer 'pointcloud'). Example: import /tmp/site.las · import /tmp/scan.e57",
            category: Category::File,
        },
        CommandSpec {
            name: "terrain",
            usage: "terrain <path.{csv|geojson}>",
            summary: "Build a terrain surface mesh on layer 'terrain'. .csv = Delaunay-triangulate x,y,z survey points (header row optional). .geojson = triangulate the vertices of elevation contour LineStrings (elevation read from the 'elevation' or 'ele' property; lon/lat projected when a location is set). Example: terrain /tmp/survey.csv",
            category: Category::Tools,
        },
        CommandSpec {
            name: "contours",
            usage: "contours <interval> [major-every]",
            summary: "Extract contour polylines FROM the terrain mesh at every multiple of <interval> (marching triangles, chained into polylines). Minor contours go on layer 'contours'; with [major-every] N, every Nth level goes on 'contours-major' instead (index contours). Needs a terrain mesh (run `terrain` first). Example: contours 0.5 5",
            category: Category::Tools,
        },
        CommandSpec {
            name: "pad",
            usage: "pad <x,y> <width> <depth> <elev> [slope]",
            summary: "Grade a flat building pad into the terrain mesh: an axis-aligned width x depth rectangle centered at x,y set to elevation <elev>, with side slopes to daylight at [slope] horizontal-run per unit rise (default 2 = a 2:1 slope). The first pad snapshots the pre-grading terrain so `cutfill` can report earthwork volumes. Needs a terrain mesh. Example: pad 10,10 20 15 3.5 2",
            category: Category::Tools,
        },
        CommandSpec {
            name: "cutfill",
            usage: "cutfill",
            summary: "Report cut and fill volumes (m3) between the current terrain and the pre-grading snapshot taken by the first `pad` — a TIN prism estimate, stored as an AnalysisReport ('cutfill', see `report`) for critique. Run `pad` first. Example: cutfill",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "lotsubdivide",
            usage: "lotsubdivide [selector] <method> [area=<> width=<> irregularity=<> seed=<>]",
            summary: "Subdivide the selected closed block curve(s) into lots on layer 'lots' (M-intemfit site planning). method=grid is recursive minimum-area OBB subdivision (splits along the block's short axis, pivoted on the long-axis midpoint, recursing while lot area > area). method=perimeter inward-offsets the block by offset_width, cuts the perimeter strip into lots with lines orthogonal to the boundary, and (when subdivide_core is on) grids the interior core — it falls back to grid when the offset collapses. method=streetfollowing (Phase 7) runs a straight-skeleton spine down the block and slices depth-limited lots off its street frontages so each lot follows the fronting street (skeleton backend selectable via lotsettings skeleton=offset|felkel; falls back to grid when the skeleton is degenerate). area = min lot area (recursion stop), width = min lot side length, irregularity 0..0.4 jitters the split pivot / perimeter samples (needs a seed to matter), seed makes the layout deterministic (replay-stable). Every lot keeps a block-boundary (street) edge. Phase-6 lot rules apply as a post-pass from the sticky settings: a width mix (lotsettings widthmix=6:0.25,8:0.5,10:0.25) re-slices the frontage by packing (hits target proportions within 5%); acute corner lots are widened (corner bonus) and clamped; slivers below sliver_frac×area are merged into their largest-shared-edge neighbour; alley loading gives two-frontage depth. When the euro_latam default profile supplies a rule value (no override), the run notes 'using euro_latam defaults (placeholder — confirm with Manuel)'. Sticky defaults come from `lotsettings`. Example: lotsubdivide last grid area=6500 width=50 · lotsubdivide grid width=40 irregularity=0.2 seed=7 · lotsubdivide perimeter area=6500 width=40",
            category: Category::Tools,
        },
        CommandSpec {
            name: "lotsettings",
            usage: "lotsettings [key=value ...]",
            summary: "Show or set the sticky lot-subdivision settings stored on the document (used by `lotsubdivide` when a run omits an arg). Keys: method (grid|perimeter|streetfollowing), area (min lot area), area_max, width (min lot side), irregularity (0..0.4, or up to 1.0 with loose), loose (on/off), force_street (1.0 = every lot must keep a street edge), seed. Phase-6 lot-rule keys: region (euro_latam|us_suburban — euro_latam carries the metric placeholder defaults), loading (front|alley), widthmix (width:proportion list e.g. 6:0.25,8:0.5,10:0.25, or off), depth (independent lot depth target) + depth_tol, corner (corner-lot width bonus, e.g. 15%) + corner_angle, flag (on/off — allow flag/panhandle lots, pole area excluded) + flag_pole, mergeslivers (on/off) + sliver_frac, alley_width. Phase-12 key: skeleton (offset|felkel — which straight-skeleton backend method=streetfollowing uses; offset is the robust default, felkel is the true convex-exact skeleton with a fallback to offset on non-convex blocks). No args prints the current settings. Settings are logged so saved files replay them. euro_latam values are placeholders pending Manuel's confirmation. Example: lotsettings area=6500 width=50 · lotsettings widthmix=6:0.25,8:0.5,10:0.25 depth=25 corner=15% · lotsettings loading=alley mergeslivers=on",
            category: Category::Tools,
        },
        CommandSpec {
            name: "lotgeneratesite",
            usage: "lotgeneratesite [selector] <pattern> [roadwidth=<> blockdepth=<> alleys=on|off seed=<>]",
            summary: "Generate a road network and blocks from the selected closed site boundary curve (M-intemfit site planning, Phase 5). pattern picks a generator — four rectilinear: orthogonal (recursive minimum-area-OBB split of the site into a grid; a spine road along each split), skewed (the same grid rotated 22.5° into a diagonal layout), organic (a gently sinusoidal spine down the site long axis plus perpendicular connectors), culdesac (a spine with perpendicular stubs ending in turnaround bulbs, spaced by block depth); plus three non-rectilinear (Phase 5b): radial (concentric ring roads + radial spokes → annular-sector blocks), hexagonal (hex lattice → hex-cell blocks), voronoi (jittered seeds, diagram as the dual of the Delaunay triangulation → irregular cell blocks). Roads bake as centerlines onto the 'roads' layer; blocks bake as outlines onto the 'blocks' layer, every block edge tagged with the street it fronts (id/width/length) so a later `lotsubdivide` on a block honours force_street_access. roadwidth = road right-of-way width (curb to curb), blockdepth = block-depth road spacing, alleys=on inserts a narrower rear-lane tier bisecting each block along its long axis, seed makes the layout deterministic (replay-stable). Sticky defaults come from `lotsettings`. Example: lotgeneratesite last orthogonal roadwidth=12 blockdepth=60 · lotgeneratesite voronoi blockdepth=70 seed=3 · lotgeneratesite culdesac blockdepth=50 alleys=on seed=7",
            category: Category::Tools,
        },
        CommandSpec {
            name: "lotloading",
            usage: "lotloading [selector] front|alley",
            summary: "Set the sticky lot loading mode (M-intemfit Phase 6): front (front-loaded — a continuous street facade, the euro_latam default) or alley (alley-loaded — two-frontage lots that run street→alley at half the block depth; takes effect when the block carries an alley edge from lotgeneratesite alleys=on). A thin convenience over `lotsettings loading=…`; the mode is sticky document state applied on the next `lotsubdivide`, so the selection is advisory. Logged so replay reproduces it. Example: lotloading alley · lotloading last front",
            category: Category::Tools,
        },
        CommandSpec {
            name: "lotsetbacks",
            usage: "lotsetbacks [selector] [front=<> side=<> rear=<> buildto=<> envelope=on|off]",
            summary: "Compute and bake the buildable envelope for the selected lot curve(s) (M-intemfit site planning, Phase 8). The envelope is the lot inset by per-edge setbacks: front from the street-fronting edge (the longest edge when the lot carries no street tag), rear from the opposite edge, side from every remaining edge. The inset is a robust per-edge half-plane clip, so non-convex/notched lots are handled and a lot too small for its setbacks collapses cleanly to nothing (reported, never a panic). front/side/rear are the setback distances (metres); buildto>0 pins the front of the envelope to a build-to line at that distance from the curb (a continuous street wall) instead of the front setback. Envelopes bake as closed curves onto the 'setbacks' layer (kept distinct from 'lots'); envelope=off computes + reports without baking. Missing args fall back to the sticky settings (lotsettings) — under the euro_latam profile the setback numbers (front 3 / side 0 party-wall / rear 3 m) are placeholders and the run notes 'confirm with Manuel'. Deterministic; logged so undo removes the envelopes and replay recreates them byte-identically. Example: lotsetbacks last front=3 side=0 rear=3 · lotsetbacks front=0 buildto=0 envelope=on",
            category: Category::Tools,
        },
        CommandSpec {
            name: "lotfrontage",
            usage: "lotfrontage [selector] [at=setback|curb]",
            summary: "Report the street frontage length of the selected lot(s), measured along the front SETBACK line by default (at=setback — Manuel's explicit ask, plan §5) or along the curb (at=curb, the street edge as drawn). The two differ on cul-de-sac bulbs and curved streets, where the outer curb arc is longer than the inset setback line — the most common reason automated layouts get rejected by reviewers, hence setback is the default. A read-only query (never logged): results go to the report plane as an AnalysisReport keyed 'lotfrontage' (count, min/avg/max, distribution, extreme lots) so `report` can re-show it and the deck can critique. Example: lotfrontage last · lotfrontage at=curb",
            category: Category::Tools,
        },
        CommandSpec {
            name: "lotreport",
            usage: "lotreport [selector] · OR lotreport compare",
            summary: "Yield report for the current intemfit layout (M-intemfit site planning, Phase 11). Summarises lots (count, total / avg / min / max area, frontage at the setback line) and — the key point — reports the site as GROSS vs NET developable area: net = gross site minus placed open-space features AND reserved blocks (the openspace:* objects on the 'openspace' layer), with the open-space ratio, because a gross number lies once open space exists. Built yield rides Phase 10: total GFA (Σ per-floor building areas read off the 'buildings' layer), building count, FAR = GFA / net developable area (the honest FAR — floor area over land you can actually build on — plus FAR gross for comparison), and lot-coverage % when footprints exist. A selector reports a subset of lots; a bare lotreport reports the whole document, taking the largest non-intemfit closed curve as the site boundary. Output is a Markdown table (renders in chat). Stored on the report plane keyed 'lotyield' so `report` / `report lotyield` re-shows it and the deck can critique grounded numbers. Run lotreport twice around a settings change, then `lotreport compare` for an A/B diff (Δ lot count, Δ GFA, Δ FAR, Δ net area, Δ open-space ratio). A read-only query — never logged. Empty/no-geometry sites report a clean 'nothing to report', never a panic. Example: lotreport · lotreport last · lotreport compare",
            category: Category::Tools,
        },
        CommandSpec {
            name: "lotopenspace",
            usage: "lotopenspace [selector] type=park|greenway|pond|treesave [area=<>] · OR reserve=<pct>",
            summary: "Place open space (M-intemfit site planning, Phase 9). Two modes, both baking onto the 'openspace' layer so a later lotreport nets them out of gross site area. DEFAULT is feature placement (Manuel's questionnaire): type picks the amenity the tool PLACES at the selected region (or, absent that, its largest empty block) — park (a small green polygon, a rounded rectangle), greenway (a linear buffered trail corridor along a selected open polyline path, or the region's long axis), pond (a rounded near-circular retention-basin footprint), treesave (a preserved-vegetation polygon following the region outline that the layout works around); area sets the feature area (m²), else a sensible fraction of the region. The SEPARATE blind %-reserve mode is owner opt-in by keyword: reserve=<pct> pulls whole blocks out of subdivision until ~pct of the site is open, biggest-and-most-central first (CityEngine's model: open space = a block you chose not to subdivide), tagging them so yield nets them out and a later lotsubdivide skips them; reserve=0 or absent = off. Advisory: feature placement is design intent, not hydrology/ecology engineering (a pond is a footprint, not a sized detention volume; a tree-save is a marked polygon, not a survey). Deterministic; logged so undo removes the geometry and replay recreates it byte-identically. Example: lotopenspace last type=park area=800 · lotopenspace last type=pond · lotopenspace last reserve=20",
            category: Category::Tools,
        },
        CommandSpec {
            name: "lotbuilding",
            usage: "lotbuilding [selector] [typology=detached|row|courtyard|slab footprint=full|coverage|inset|typology floors=<> floorheight=<> coverage=<> roof=flat|gable|hip|shed|auto pitch=<> stepback=<>]",
            summary: "Generate buildings inside each selected lot's buildable envelope (M-intemfit site planning, Phase 10). For every selected closed lot curve the tool computes the Phase-8 buildable envelope (the lot inset by front/side/rear setbacks), derives a footprint, extrudes it to a stepped 3D mass, and caps it with a roof — baking three objects per lot (footprint 2D curve, mass 3D mesh, roof 3D mesh) onto the 'buildings' layer. typology drives the footprint shape: detached (a compact mass centred in the envelope), row/terrace (fills the full lot width — party-wall, matching euro_latam side=0 medianería), courtyard (a ring footprint with an interior void), slab (a large single apartment mass). footprint picks the fill mode: full (footprint = envelope), coverage (a centred footprint of coverage×lot area — lot-coverage %), inset (envelope pulled in a fixed margin), typology (the typology decides — the DEFAULT). Height is FIXED = floors × floorheight; floors above the step-back start inset by stepback metres per floor (stepped/wedding-cake massing). roof is flat/gable/hip/shed, or auto (per-typology: detached/row→gable, courtyard/slab→flat); pitch is the roof slope in degrees. Per-floor areas are stored on the result so a later lotreport (Phase 11) can total GFA (Σ floor areas, net of step-backs) and FAR (GFA/site). Missing args fall back to sticky lotsettings; under the euro_latam profile floor height (3 m) / roof pitch (30°) / coverage are placeholders and the run notes 'confirm with Manuel'. A lot whose envelope collapses (setbacks exceed it) is skipped and reported, never a panic. Deterministic; logged so undo removes the buildings and replay recreates them byte-identically. Example: lotbuilding last typology=row floors=3 roof=gable pitch=35 · lotbuilding typology=slab footprint=coverage coverage=0.6 floors=8 stepback=2 roof=flat",
            category: Category::Tools,
        },
        CommandSpec {
            name: "plant",
            usage: "plant <species> <x,y[,z]> [age-years]",
            summary: "Place one plant from the embedded 33-species catalog: temperate ornamentals (quercus-robur, acer-rubrum, betula-pendula, pinus-sylvestris, tilia-cordata) plus tropical/subtropical packs — Caribbean (royal/coconut palm, ceiba, flamboyan, mango), Valle del Cauca (saman, guadua bamboo, gualanday), Guayaquil (guayacan amarillo, algarrobo, palo santo, ceibo). Common-name substrings like 'oak' or 'palm' work too. Renders a trunk + canopy mesh named 'plant:<id>' on layer 'planting', draped onto the terrain when one exists; palms render as crown-on-trunk for low-sun shadow accuracy. [age-years] scales height and canopy along the species growth rate (default mature). If the doc has a `location`, planting outside the species' climate band prints an advisory. Use `plantcatalog [region|zone]` to browse. Planted canopies occlude sun like any mesh. Example: plant royal-palm 10,5 · plant oak 10,5 25",
            category: Category::Tools,
        },
        CommandSpec {
            name: "plantrow",
            usage: "plantrow <species> <a x,y> <b x,y> <spacing>",
            summary: "A row of plants from a to b, one every <spacing> meters (b included when the length is an exact multiple). Same catalog, draping and layer as `plant`. Example: plantrow tilia 0,0 30,0 6",
            category: Category::Tools,
        },
        CommandSpec {
            name: "plantschedule",
            usage: "plantschedule <path.csv>",
            summary: "Export a planting schedule CSV (species id, botanical + common name, count, mature height, canopy spread, deciduous flag) counting every 'plant:*' object on layer 'planting', and store an AnalysisReport ('plantschedule', see `report`). Example: plantschedule /tmp/planting.csv",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "plantcatalog",
            usage: "plantcatalog [region|zone]",
            summary: "List catalog species, optionally filtered by a native-region tag (caribbean, valle-del-cauca, guayaquil, europe, north-america, temperate, subtropical) or a Köppen zone code (Af, Am, Aw, Cfa, Cwa, Cfb, Dfb). Prints id, common + botanical name, mature size, climate zones and Miyawaki layer. Query only — no geometry. Example: plantcatalog caribbean · plantcatalog Aw",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "miyawaki",
            usage: "miyawaki <closed-region> [density]",
            summary: "Grow a dense native Miyawaki mini-forest inside a closed region. Picks only species native/suited to the document's climate band (derived from `location` latitude) that carry a stratification layer, spreads them across canopy/tree/subtree/shrub (10/40/30/20%), and seed-places 3–5 stems/m² (scaled by [density], default 4) as saplings — adjacent stems differ in species and layer, never rows. Emits one 'plant:*' mesh per stem on layer 'planting' and stores an AnalysisReport ('miyawaki', see `report`). Seeded from the region so replay is byte-stable. Warns when too few natives exist for the location; advisory: dense planting self-thins 30–50% over time (intended). Needs a closed region; set `location` first. Example: miyawaki last 3",
            category: Category::Tools,
        },
        CommandSpec {
            name: "flowarrows",
            usage: "flowarrows [n]",
            summary: "Drainage direction visualization: steepest-descent arrow glyphs on the [n] largest terrain faces (default 200) on layer 'analysis', plus an AnalysisReport ('flowarrows') of face slopes. A gradient picture only — visualization, not hydrology engineering. Needs a terrain mesh. Example: flowarrows 100",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "ponding",
            usage: "ponding",
            summary: "Mark potential ponding spots: a circle marker at every interior terrain vertex lower than all its neighbors (local minima where water could collect), on layer 'analysis', plus an AnalysisReport ('ponding') of sink depths. Local-minima detection only — visualization, not hydrology engineering. Example: ponding",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sitepath",
            usage: "sitepath <curve-selector> <width>",
            summary: "Hardscape path: a <width>-wide ribbon mesh following the selected curve (line, polyline, arc, circle...), draped onto the terrain surface, on layer 'hardscape'. Reports the max grade and warns where it exceeds the 1:12 accessible slope — advisory, not a code check. Example: sitepath last 1.5",
            category: Category::Tools,
        },
        CommandSpec {
            name: "osmfile",
            usage: "osmfile <path.json>",
            summary: "Build OpenStreetMap building context from a saved Overpass API JSON export ('out geom;' query): each building-tagged way footprint is extruded (height tag, else building:levels x 3 m, else 9 m) into a mesh on layer 'context'. lon/lat projected to local meters when a location is set. Example: osmfile /tmp/overpass.json",
            category: Category::Tools,
        },
        CommandSpec {
            name: "distance",
            usage: "distance <a x,y,z> <b x,y,z>",
            summary: "Measure the distance between two points (query only, nothing is created). Example: distance 0,0,0 3,4,0",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "area",
            usage: "area <selector>",
            summary: "Measure area: closed curves report the enclosed XY area, meshes their total surface area (query only). Example: area last",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "volume",
            usage: "volume <selector>",
            summary: "Measure the volume of solid meshes (query only). Example: volume last",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "bbox",
            usage: "bbox <selector>",
            summary: "Report the combined bounding box (min, max, size) of objects (query only). Example: bbox all",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "schedule",
            usage: "schedule [layer]",
            summary: "Print a schedule table (name/id/layer/type/area/volume) for all objects or a layer's objects, grouped by name (query only). Example: schedule · schedule walls",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "dataextract",
            usage: "dataextract [by count|instance] [to <path.csv>]",
            summary: "Extract block-instance data (AutoCAD DATAEXTRACTION / BOM): tabulate block instances grouped by definition, with a count and every distinct param/attribute value they carry. `by count` (default) gives one aggregated row per block definition (a param cell shows the shared value, or '(varies)'); `by instance` gives one row per placement. Prints a table, or writes a .csv with `to <path>`. Query only. Aliases: dataextraction, bom. Example: dataextract · dataextract by instance to /tmp/bom.csv",
            category: Category::Analyze,
        },
        CommandSpec {
            name: "sheettable",
            usage: "sheettable <sheet> [layer]",
            summary: "Place a schedule table on a sheet; the table is rendered as a text grid in the PDF at print time. Example: sheettable plan · sheettable plan walls",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "sheetdim",
            usage: "sheetdim <sheet> <x1,y1> <x2,y2> [offset_mm]",
            summary: "Add a paper-space linear dimension to a sheet; a and b are paper coordinates in mm, offset is the perpendicular dim-line offset in mm (default 8). The numeric label is derived from the model distance via the view scale. Example: sheetdim plan 20,30 120,30 10",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "sheettext",
            usage: "sheettext <sheet> <x,y> <text...> [height_mm]",
            summary: "Add a scale-independent paper-space text note to a sheet; position is paper mm from the lower-left, height is the cap height in mm ON PAPER (default 2.5) so the note is the same physical size in every viewport regardless of scale. Example: sheettext plan 20,180 FIRST FLOOR PLAN 5",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "sheetleader",
            usage: "sheetleader <sheet> <tipx,y> <kneex,y> <textx,y> <text...> [height_mm]",
            summary: "Add a paper-space leader (arrow tip → knee → text) to a sheet; all points are paper mm, height is mm on paper (default 2.5). Scale-independent. Example: sheetleader plan 40,40 55,55 60,55 SEE DETAIL 2.5",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "sheettag",
            usage: "sheettag <sheet> <x,y> <text> [bubble|square|diamond]",
            summary: "Add a paper-space callout/tag (shaped bubble + centered text) to a sheet; position is the bubble center in paper mm, shape defaults to bubble. Use for grid bubbles, detail numbers, keynotes. Scale-independent. Example: sheettag plan 30,30 A · sheettag plan 90,90 3 diamond",
            category: Category::Dimension,
        },
        CommandSpec {
            name: "view",
            usage: "view save <name> | view <name> | view list",
            summary: "Named views: save the active viewport camera, restore it later, or list saved views. Example: view save entry then view entry",
            category: Category::View,
        },
        CommandSpec {
            name: "camera",
            usage: "camera <2point|persp|pano|fisheye [fov]|phone [lens]|<mm>>",
            summary: "Set the active viewport's projection (view state, not logged). '2point' = architectural two-point perspective (verticals stay vertical); 'persp' = normal perspective; 'pano'/'360' = equirectangular 360° panorama; 'fisheye [deg]' = equidistant fisheye at the given field of view (default 180°); a focal length like '35' or '35mm' sets a full-frame lens; 'phone [lens]' simulates a real phone lens (iphone-main, iphone-ultrawide, iphone-tele, pixel-main, galaxy-tele, …). Example: camera 2point · camera fisheye 200 · camera phone iphone-ultrawide",
            category: Category::View,
        },
        CommandSpec {
            name: "block",
            usage: "block <selector> <name>",
            summary: "Capture the geometry of selected objects as a named reusable block definition (like a symbol/component). Inputs stay in the scene; the definition is a geometry snapshot. Example: block last door · block last 3 tree (architect: door, window, tree, column, stair)",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "insert",
            usage: "insert <name> <position x,y,z> [rotation_deg] [scale] [param=value ...]",
            summary: "Place an instance of a named block at a point with optional rotation (degrees CCW about Z), uniform scale, and — for dynamic blocks — param overrides. Example: insert door 3,0,0 · insert tree 10,5,0 0 0.8 · insert pdoor 0,0,0 width=1.2",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "pblock",
            usage: "pblock <name> [param=default ...] : templ ; templ ; ...",
            summary: "Define a dynamic (parametric) block: named params with defaults plus a command-template body ({param} substitution). Instances bake geometry at their own param values, editable via 'param'. Example: pblock pdoor width=0.9 : rect 0,0,0 {width} 0.05 ; line {width},0,0 {width},{width},0",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "param",
            usage: "param <selector> <key=value ...>",
            summary: "Edit a parameter of a selected dynamic-block instance; its geometry re-derives from the template. Example: param last width=1.2 · param last swing=45",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "paramset",
            usage: "paramset <selector> <key=value ...>",
            summary: "Edit a parameter of a selected built-in parametric structure (geodesic, hypar, gaussvault, gridshell, funicular, tensegrity, cablenet, spaceframe); its mesh re-derives live. These generators stay editable after creation. Example: paramset last frequency=4 · paramset last rise=5",
            category: Category::Structure,
        },
        CommandSpec {
            name: "freeze",
            usage: "freeze <selector>",
            summary: "Flatten selected parametric structures to plain static meshes (alias: bake): keeps the geometry but drops the generator + params, so they leave the Parameters tab and are no longer editable. Example: freeze last · freeze sel",
            category: Category::Structure,
        },
        CommandSpec {
            name: "blockdelete",
            usage: "blockdelete <name>",
            summary: "Delete a block definition (plain or parametric). Refuses while instances of it exist — delete the instances first. Example: blockdelete door",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "blocks",
            usage: "blocks",
            summary: "List all block definitions with their geometry counts (query only). Example: blocks",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "xref",
            usage: "xref attach <path> [at x,y,z] [scale s] [rot deg] | xref list | xref reload <name> | xref detach <name>",
            summary: "External reference: link another drawing file into this document as a reloadable referenced instance (an xref is a block whose contents came from another file). 'attach' imports the file's geometry into a block named from the path stem and places one instance under the transform; 'list' shows attached xrefs; 'reload' re-reads the file and rebuilds the definition (placements kept); 'detach' removes the instances + definition. Example: xref attach site.dxf at 0,0,0 · xref reload site · xref detach site",
            category: Category::File,
        },
        CommandSpec {
            name: "ncopy",
            usage: "ncopy <instance-selector> <index>",
            summary: "Copy ONE nested object out of an xref/block instance into this document as a real, independent object, transformed by the instance's placement; the source instance stays intact (AutoCAD NCOPY). <index> is the 0-based sub-object of the block definition. Example: ncopy last 0",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "xclip",
            usage: "xclip <instance-selector> <min x,y> <max x,y> | xclip <instance-selector> off",
            summary: "Clip a block/xref instance to a rectangular boundary (world XY) so only the geometry inside the rect renders (AutoCAD XCLIP). Give two opposite corners to set the clip; 'off' clears it. Corners may be in any order. Undoable. Example: xclip last 0,0 10,10 · xclip last off",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "workdir",
            usage: "workdir [path]",
            summary: "Show or grant the scoped deck workdir — a single user-chosen folder the deck may list and import files from (NOT the whole filesystem, NOT a shell). No arg prints the current grant; 'workdir <path>' grants that folder (persisted to ~/.config/itsjustcad/workdir.txt). Once granted, 'files' lists importable files and 'import <name>' resolves a bare file name inside it (path-traversal guarded: '..', absolute paths and separators are refused). Example: workdir ~/Drawings · workdir",
            category: Category::File,
        },
        CommandSpec {
            name: "files",
            usage: "files",
            summary: "List the importable files in the granted deck workdir (query only). Import one with 'import <name>'. Errors clearly if no workdir is set (grant one with 'workdir <path>'). Example: files",
            category: Category::File,
        },
        CommandSpec {
            name: "blocklib",
            usage: "blocklib [list]",
            summary: "List block names in the on-disk library (~/.config/itsjustcad/blocks/). Example: blocklib",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "blockload",
            usage: "blockload <name>",
            summary: "Load a library block into the document as a named definition ready to insert. Example: blockload tree · blockload door-single",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "blocksave",
            usage: "blocksave <name> [description]",
            summary: "Save the named block definition from the document back to the library. Example: blocksave my-column 'precast column 400mm'",
            category: Category::Annotate,
        },
        CommandSpec {
            name: "select",
            usage: "select <selector>",
            summary: "Set the selection. Example: select all",
            category: Category::Edit,
        },
        CommandSpec {
            name: "selectnone",
            usage: "selectnone",
            summary: "Clear the selection",
            category: Category::Edit,
        },
        CommandSpec {
            name: "undo",
            usage: "undo",
            summary: "Undo the last geometry command",
            category: Category::Edit,
        },
        CommandSpec {
            name: "redo",
            usage: "redo",
            summary: "Redo",
            category: Category::Edit,
        },
        CommandSpec {
            name: "amend",
            usage: "amend <step> <command...>",
            summary: "Rewrite history: replace the op at <step> (0 = first op) with a new command and replay the whole log; later ops rebuild against the change. On failure nothing changes. Example: amend 0 box 0,0,0 8,8,3",
            category: Category::Edit,
        },
        CommandSpec {
            name: "option",
            usage: "option save <name> | option <name> | option list | option delete <name>",
            summary: "Design options: named branches of the op-log for comparing schemes. 'option save tower' snapshots the current model as a branch; 'option courtyard' switches to (replays) another branch, auto-saving in-progress work to the branch you leave first; 'option list' shows branches (* = current); 'option delete <name>' removes one. Example: box 0,0,0 5,5,20 then option save tower",
            category: Category::Edit,
        },
        CommandSpec {
            name: "material",
            usage: "material <name> <elastic-modulus-E> <density>",
            summary: "Define a named structural material (stored for interoperability, never analyzed here). E in Pa, density in kg/m³. Example: material steel 200e9 7850 · material concrete 30e9 2400",
            category: Category::Structure,
        },
        CommandSpec {
            name: "grid",
            usage: "grid <name> x A:0 B:5 ... y 1:0 2:4 ... [levels 0,3,6]",
            summary: "Define a labeled reference grid: X axes and Y axes as label:coord pairs, plus optional level elevations. Rendered as reference lines. Example: grid main x A:0 B:6 C:12 y 1:0 2:5 levels 0,3.5,7",
            category: Category::Structure,
        },
        CommandSpec {
            name: "story",
            usage: "story <name> <elevation> [height <h>]",
            summary: "Define a building story/level by name and base elevation (meters), with an optional floor-to-floor height used by 'fromlayer … level'. Stored sorted by elevation. 'level' is an alias. Example: story L1 0 height 3.5 · level L2 3.5 height 3",
            category: Category::Structure,
        },
        CommandSpec {
            name: "levels",
            usage: "levels",
            summary: "List the defined building stories/levels (name, elevation, height). Query only. Example: levels",
            category: Category::Structure,
        },
        CommandSpec {
            name: "fromlayer",
            usage: "fromlayer <layer> wall thick <t> [height <h> | level <name>]",
            summary: "Drawings→BIM: turn the 2D curves on a layer into typed BIM walls, one per curve, extruded vertically from the level base to base+height and 't' meters thick. The walls export as IFCWALL. Give an explicit 'height <h>' (base at Z=0) or a named 'level <name>' whose elevation is the base and whose height is the rise. Example: fromlayer WALLS wall thick 0.2 height 3 · fromlayer A-WALL wall thick 0.15 level L1",
            category: Category::Structure,
        },
        CommandSpec {
            name: "room",
            usage: "room <closed-curve> <occupancy> [name]",
            summary: "Tag a closed-curve region with an IBC use group (assembly|business|residential|mercantile|educational|storage|institutional) and its computed plan area. Rooms feed the IBC occupant-load / exit-count / travel-distance compliance checks (codecheck ibc2021). Example: room sel business · room #suite assembly Lobby",
            category: Category::Structure,
        },
        CommandSpec {
            name: "rooms",
            usage: "rooms",
            summary: "List the tagged occupancy regions (name, use group, area). Query only. Example: rooms",
            category: Category::Structure,
        },
        CommandSpec {
            name: "beam",
            usage: "beam <a x,y,z> <b x,y,z> <section> [material <m>] [rot <deg>]",
            summary: "Frame member (horizontal): sweep a named section along the line a→b into a solid. Optional material and roll angle (deg). Example: beam 0,0,3 6,0,3 W12 material steel · beam 0,0,3 6,0,3 col rot 90",
            category: Category::Structure,
        },
        CommandSpec {
            name: "column",
            usage: "column <a x,y,z> <b x,y,z> <section> [material <m>] [rot <deg>]",
            summary: "Frame member (vertical): sweep a named section along the line a→b into a solid. Same as beam, distinct for scheduling/ergonomics. Example: column 0,0,0 0,0,3.5 col material concrete",
            category: Category::Structure,
        },
        CommandSpec {
            name: "slab",
            usage: "slab <p1> <p2> <p3> ... thick <t> [material <m>]",
            summary: "Area member: extrude a closed boundary upward (+Z) by thickness into a floor slab. Example: slab 0,0 6,0 6,4 0,4 thick 0.2 material concrete",
            category: Category::Structure,
        },
        CommandSpec {
            name: "wall",
            usage: "wall <p1> <p2> <p3> ... thick <t> [material <m>]",
            summary: "Area member: extrude a closed boundary along its horizontal normal by thickness into a wall. Example: wall 0,0 6,0 6,0.2 0,0.2 thick 3 material concrete",
            category: Category::Structure,
        },
        CommandSpec {
            name: "load",
            usage: "load <point|line|area> [name] <target/point(s)> <magnitude> <dx,dy,dz>",
            summary: "Record a structural load (data + overlay arrow; no analysis). point = concentrated force at a node (N); line = distributed along a member (N/m); area = pressure on a surface (Pa). Direction is a world-space vector. Example: load point dead 0,0,3 10000 0,0,-1 · load line live 0,0,3 6,0,3 5000 0,0,-1 · load area wind 0,0,0 6,0,0 6,4,0 0,4,0 end 2000 1,0,0",
            category: Category::Structure,
        },
        CommandSpec {
            name: "support",
            usage: "support <x,y,z> <pinned|fixed|roller> [axis dx,dy,dz]",
            summary: "Record a structural support / boundary condition (data + overlay symbol; no analysis). pinned = all translations fixed; fixed = all 6 DOFs fixed; roller = one translation free (provide the free axis). Example: support 0,0,0 pinned · support 6,0,0 roller 1,0,0 · support 3,3,0 fixed",
            category: Category::Structure,
        },
    ]
}

/// Selector grammar shared by help and the LLM prompt.
pub const SELECTOR_HELP: &str =
    "Selectors: 'last' (most recent object), 'last N' (N most recent), 'all', 'sel' (current selection), or an object name.";
