[package]
name = "mydrafter"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mydrafter"
path = "src/main.rs"

[dependencies]
mydrafter-doc.workspace = true
kernel-curve.workspace = true
mydrafter-commands.workspace = true
mydrafter-deck.workspace = true
mydrafter-render.workspace = true
kernel-mesh.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
eframe.workspace = true
glam.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rfd.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
egui_commonmark = "0.24"
