// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright © 2026 Hector Tarrido-Picart

//! Blind %-reserve open space (plan §1, §9 Phase 9) — owner opt-in keyword.
//!
//! `lotopenspace [site-sel] reserve=<pct>` pulls whole BLOCKS out of
//! subdivision until ~`pct` of the SITE area is open, **biggest-and-most-central
//! first** (CityEngine's model: open space = a block you chose not to
//! subdivide). Reserved blocks come back tagged so yield nets them out and a
//! later `lotsubdivide` skips them.
//!
//! Determinism: the block set comes from the deterministic street generator
//! (seeded), and the selection order is a total sort (score, then a positional
//! tiebreak), so the same site + settings always reserve the same blocks.

use crate::blocks::block::Block;
use crate::geometry::polygon2d::Polygon2d;
use crate::settings::SubdivisionSettings;
use crate::streets::{extract_blocks, generate_streets};
use glam::DVec2;

/// A block chosen for reservation, with the score that selected it.
#[derive(Debug, Clone)]
pub struct ReservedBlock {
    /// The reserved block polygon (open space).
    pub polygon: Polygon2d,
    /// Selection score = normalised (area · centrality). Higher = picked first.
    pub score: f64,
}

/// The outcome of a blind %-reserve run.
#[derive(Debug, Clone)]
pub struct ReserveResult {
    /// Blocks pulled out as open space (biggest-and-most-central first).
    pub reserved: Vec<ReservedBlock>,
    /// The remaining developable blocks (what a subsequent `lotsubdivide`
    /// should operate on — the reserved ones excluded).
    pub developable: Vec<Polygon2d>,
    /// Total site area (gross).
    pub site_area: f64,
    /// Total reserved area (open space).
    pub reserved_area: f64,
    /// Requested reserve fraction (0..1).
    pub requested_frac: f64,
}

impl ReserveResult {
    /// Achieved reserved fraction of the site.
    pub fn achieved_frac(&self) -> f64 {
        if self.site_area > 0.0 {
            self.reserved_area / self.site_area
        } else {
            0.0
        }
    }
}

/// Run a blind %-reserve on `site` under `settings`, reserving whole blocks
/// until ~`frac` (0..1) of the site area is open, biggest-and-most-central
/// first. Blocks are generated by the deterministic street generator, so the
/// reservation is replay-stable for a fixed seed.
///
/// `frac <= 0` reserves nothing (feature-placement mode / off). `frac` is
/// clamped to `[0, 0.9]` — reserving the whole site is the ruled-out "no
/// subdivision" mode.
pub fn reserve_blocks(site: &Polygon2d, frac: f64, settings: &SubdivisionSettings) -> ReserveResult {
    let site_area = site.area();
    let frac = frac.clamp(0.0, 0.9);

    let empty = ReserveResult {
        reserved: Vec::new(),
        developable: Vec::new(),
        site_area,
        reserved_area: 0.0,
        requested_frac: frac,
    };
    if frac <= 0.0 || site_area <= 1e-6 {
        return empty;
    }

    // Deterministic block set from the street generator.
    let graph = generate_streets(site, settings);
    if graph.is_empty() {
        return empty;
    }
    let blocks: Vec<Block> = extract_blocks(site, &graph, settings);
    if blocks.is_empty() {
        return empty;
    }

    // Score each block: large AND central. Normalise area by the max block
    // area, centrality by 1 − (dist(centroid, site centroid) / diag). The two
    // are multiplied so a huge peripheral block does not always beat a large
    // central one — "biggest-AND-most-central".
    let site_c = site.centroid();
    let (lo, hi) = site.aabb();
    let diag = (hi - lo).length().max(1e-6);
    let max_area = blocks.iter().map(|b| b.area()).fold(1e-9, f64::max);

    struct Scored {
        idx: usize,
        area: f64,
        score: f64,
        c: DVec2,
    }
    let mut scored: Vec<Scored> = blocks
        .iter()
        .enumerate()
        .map(|(idx, b)| {
            let area = b.area();
            let c = b.centroid();
            let centrality = 1.0 - (c.distance(site_c) / diag).min(1.0);
            let score = (area / max_area) * centrality;
            Scored { idx, area, score, c }
        })
        .collect();

    // Total-order sort: score desc, then a stable positional tiebreak
    // (quantised centroid) so equal scores are deterministic across platforms.
    scored.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| quant(a.c).cmp(&quant(b.c)))
    });

    let target_area = site_area * frac;
    let mut reserved = Vec::new();
    let mut reserved_area = 0.0;
    let mut reserved_idx = vec![false; blocks.len()];
    for s in &scored {
        if reserved_area >= target_area {
            break;
        }
        reserved_idx[s.idx] = true;
        reserved_area += s.area;
        reserved.push(ReservedBlock {
            polygon: blocks[s.idx].polygon.clone(),
            score: s.score,
        });
        // Stop as soon as we cross the target — "~pct", biggest-first, so the
        // first block that reaches it is where we stop (never over-reserve past
        // one block's worth once already at/above target).
    }

    let developable: Vec<Polygon2d> = blocks
        .iter()
        .enumerate()
        .filter(|(i, _)| !reserved_idx[*i])
        .map(|(_, b)| b.polygon.clone())
        .collect();

    ReserveResult {
        reserved,
        developable,
        site_area,
        reserved_area,
        requested_frac: frac,
    }
}

/// Quantise a point to millimetre-ish integers for a deterministic tiebreak.
fn quant(p: DVec2) -> (i64, i64) {
    ((p.x * 1000.0).round() as i64, (p.y * 1000.0).round() as i64)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::settings::StreetPattern;

    fn site(w: f64, h: f64) -> Polygon2d {
        Polygon2d::from_pairs([(0.0, 0.0), (w, 0.0), (w, h), (0.0, h)]).unwrap()
    }

    fn gen_settings() -> SubdivisionSettings {
        SubdivisionSettings {
            street_pattern: StreetPattern::Orthogonal,
            road_width: 10.0,
            block_depth: 60.0,
            seed: 7,
            ..SubdivisionSettings::default()
        }
    }

    #[test]
    fn reserve_zero_is_off() {
        let s = site(400.0, 300.0);
        let r = reserve_blocks(&s, 0.0, &gen_settings());
        assert!(r.reserved.is_empty());
        assert_eq!(r.reserved_area, 0.0);
    }

    #[test]
    fn reserve_twenty_percent_is_near_target() {
        let s = site(600.0, 400.0);
        let r = reserve_blocks(&s, 0.20, &gen_settings());
        assert!(!r.reserved.is_empty(), "some blocks reserved");
        // Achieved within a block's granularity of 20 %. Whole-block reservation
        // is coarse, so tolerate generous slack but prove it is in the ballpark.
        let f = r.achieved_frac();
        assert!(f > 0.08 && f < 0.40, "achieved frac {f}");
        // Reserved + developable == all blocks (nothing lost).
        let total: f64 = r.reserved_area + r.developable.iter().map(|p| p.area()).sum::<f64>();
        let all_blocks: f64 = {
            let graph = generate_streets(&s, &gen_settings());
            extract_blocks(&s, &graph, &gen_settings())
                .iter()
                .map(|b| b.area())
                .sum()
        };
        assert!((total - all_blocks).abs() < 1e-6, "conservation");
    }

    #[test]
    fn reserved_blocks_are_larger_and_central() {
        let s = site(600.0, 400.0);
        let r = reserve_blocks(&s, 0.20, &gen_settings());
        assert!(!r.reserved.is_empty());
        // The reserved blocks' mean area should exceed the developable mean —
        // "biggest first".
        let res_mean =
            r.reserved.iter().map(|b| b.polygon.area()).sum::<f64>() / r.reserved.len() as f64;
        if !r.developable.is_empty() {
            let dev_mean =
                r.developable.iter().map(|p| p.area()).sum::<f64>() / r.developable.len() as f64;
            assert!(res_mean >= dev_mean * 0.9, "reserved {res_mean} vs dev {dev_mean}");
        }
        // Reserved centroid should sit nearer the site centre than the mean
        // developable centroid.
        let site_c = s.centroid();
        let res_d = r
            .reserved
            .iter()
            .map(|b| b.polygon.centroid().distance(site_c))
            .sum::<f64>()
            / r.reserved.len() as f64;
        if !r.developable.is_empty() {
            let dev_d = r
                .developable
                .iter()
                .map(|p| p.centroid().distance(site_c))
                .sum::<f64>()
                / r.developable.len() as f64;
            assert!(res_d <= dev_d + 1e-6, "reserved central: {res_d} vs {dev_d}");
        }
    }

    #[test]
    fn reserve_is_deterministic() {
        let s = site(600.0, 400.0);
        let a = reserve_blocks(&s, 0.25, &gen_settings());
        let b = reserve_blocks(&s, 0.25, &gen_settings());
        assert_eq!(a.reserved.len(), b.reserved.len());
        for (x, y) in a.reserved.iter().zip(&b.reserved) {
            assert_eq!(x.polygon.verts(), y.polygon.verts());
        }
    }

    #[test]
    fn developable_excludes_reserved_and_subdivides() {
        // The reserved blocks must NOT appear in the developable set, and the
        // developable set (what a later lotsubdivide runs on) is non-empty and
        // subdividable — proving reserved blocks are skipped by subdivision.
        let s = site(600.0, 400.0);
        let settings = gen_settings();
        let r = reserve_blocks(&s, 0.20, &settings);
        assert!(!r.reserved.is_empty());
        assert!(!r.developable.is_empty(), "some blocks stay developable");
        // No developable block equals a reserved block (disjoint sets).
        for dev in &r.developable {
            for res in &r.reserved {
                assert_ne!(dev.verts(), res.polygon.verts(), "reserved leaked into developable");
            }
        }
        // Every developable block subdivides into ≥1 lot.
        let sub = SubdivisionSettings {
            lot_area_min: 1500.0,
            lot_width_min: 15.0,
            force_street_access: 0.0,
            ..settings.clone()
        };
        let lots: usize = r
            .developable
            .iter()
            .map(|b| crate::subdivide(b, &sub).len())
            .sum();
        assert!(lots >= r.developable.len(), "developable blocks subdivide");
    }

    #[test]
    fn reserve_capped_at_ninety_percent() {
        let s = site(600.0, 400.0);
        let r = reserve_blocks(&s, 5.0, &gen_settings());
        // Clamped: never reserves the whole site (leaves some developable).
        assert!(r.requested_frac <= 0.9);
    }
}
